Repository software-mansion/protostar, pull requests merged in 2022-10, with the labels that each got.

#909 Add auto-assign size-label action
  .github/workflows/assign_size_label.yml
Labels: size/S

#907 Skip checking for upgrades on `upgrade` command
  protostar/protostar_cli.py
  tests/e2e/test_upgrading.py
Labels: size/S

#904 Introduce runtime constants for builds
  protostar.spec
  protostar/composition_root.py
  protostar/protostar_cli.py
  protostar/protostar_cli_test.py
  protostar/protostar_toml/protostar_toml_version_checker.py
  protostar/protostar_toml/protostar_toml_version_checker_test.py
  protostar/utils/protostar_directory.py
  pyproject.toml
  scripts/deploy.py
  scripts/write_runtime_constants.py
  tests/e2e/conftest.py
  tests/e2e/test_misc_commands.py
Labels: size/L

#917 Fix size label action
  .github/workflows/assign_size_label.yml
Labels: size/S

#920 Fixed flaky map and filter test
  tests/integration/fuzzing_strategies/map_and_filter_test.cairo
Labels: size/XS

#919 Add constants.json to gitignore
  .gitignore
Labels: size/XS

#918 Don't panic when `constants.json` doesn't exist
  protostar/utils/protostar_directory.py
Labels: size/S

#923 update `CODEOWNERS`
  .github/CODEOWNERS
Labels: size/XS

#922 Discourage installing packages from mainline
  protostar/commands/install/install_command.py
  protostar/commands/update/update_package.py
  protostar/git/git_repository.py
  tests/e2e/test_package_management.py
  website/docs/cli-reference.md
  website/docs/tutorials/05-dependencies-management.md
Labels: size/M

#929 Fix fee arg type
  protostar/cli/argument_parser_facade.py
Labels: size/M

#927 Update migration docs
  website/docs/tutorials/06-deploying/02-migrations/README.md
  website/docs/tutorials/06-deploying/02-migrations/deploy-contract.md
Labels: size/S

#933 Minor docs updates
  website/docs/tutorials/03-project-initialization.md
  website/docs/tutorials/06-deploying/01-cli.md
Labels: size/S

#937 Fix build binaries step
  .github/workflows/build_binaries.yml
Labels: size/XS

#926 Added git e2e tests
  tests/e2e/test_package_management.py
Labels: size/S

#916 Drop building in migrations
  protostar/commands/build_command.py
  protostar/commands/migrate_command.py
  protostar/commands/migrate_command_test.py
  protostar/compiler/project_compiler.py
  protostar/migrator/cheatcodes/migrator_declare_cheatcode.py
  protostar/migrator/cheatcodes/migrator_deploy_contract_cheatcode.py
  protostar/migrator/migrator.py
  protostar/migrator/migrator_contract_identifier_resolver.py
  protostar/migrator/migrator_execution_environment.py
  protostar/migrator/migrator_test.py
  protostar/testing/cheatcodes/declare_cheatcode.py
  protostar/testing/cheatcodes/deploy_contract_cheatcode.py
  tests/e2e/test_building.py
  tests/e2e/test_migrating.py
  tests/integration/migrator/migrator_call_cheatcode_test.py
  tests/integration/migrator/migrator_declare_cheatcode_test.py
  tests/integration/migrator/migrator_deploy_contract_cheatcode_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/06-deploying/02-migrations/declare.md
  website/docs/tutorials/06-deploying/02-migrations/deploy-contract.md
  website/docs/tutorials/07-testing/02-cheatcodes/declare.md
  website/docs/tutorials/07-testing/02-cheatcodes/deploy-contract.md
Labels: size/M

#901 Redesigning `protostar.toml` 10 — Rolling integration — `ArgumentValueProvider`
  protostar/cli/__init__.py
  protostar/cli/argument_parser_facade.py
  protostar/cli/argument_parser_facade_test.py
  protostar/cli/argument_value_from_config_provider.py
  protostar/cli/argument_value_from_config_provider_test.py
  protostar/cli/argument_value_from_config_provider_test/protostar.toml
  protostar/cli/command_names_delayed_provider.py
  protostar/cli/command_names_delayed_provider_test.py
  protostar/cli/config_file_argument_resolver.py
  protostar/composition_root.py
  protostar/configuration_file/__init__.py
  protostar/configuration_file/argument_value_resolver.py
  protostar/configuration_file/argument_value_resolver_test.py
  protostar/configuration_file/configuration_file.py
  protostar/configuration_file/configuration_file_factory.py
  protostar/configuration_file/configuration_file_factory_test.py
  protostar/configuration_file/configuration_file_v1.py
  protostar/configuration_file/configuration_file_v1_test.py
  protostar/configuration_file/configuration_file_v2.py
  protostar/configuration_file/configuration_file_v2_migrator_test.py
  protostar/configuration_file/configuration_file_v2_test.py
  protostar/start.py
  protostar/start_test.py
Labels: size/L

#895 Add `--last-failed` option
  protostar/commands/test/test_command.py
  protostar/commands/test/test_command_cache.py
  protostar/self/cache_io.py
  protostar/self/cache_io_test.py
  protostar/starknet/cache.py
  tests/data/tests.py
  tests/integration/protostar_fixture.py
  tests/integration/testing_cache/test_cache.py
  website/docs/cli-reference.md
Labels: size/M

#931 Use fast pedersen hash in VM
  protostar/__init__.py
Labels: size/XS

#940 Add message to l2 cheatcode
  protostar/testing/cheatcodes/send_message_to_l2.py
  protostar/testing/environments/common_test_cheatcode_factory.py
  tests/integration/cheatcodes/send_message_to_l2/external_contract_with_l1_handler.cairo
  tests/integration/cheatcodes/send_message_to_l2/send_message_to_l2_test.py
  tests/integration/cheatcodes/send_message_to_l2/simple_l1_handler_test.cairo
  tests/integration/protostar_fixture.py
Labels: size/M

#948 `send_message_to_l2` docs
  website/docs/tutorials/07-testing/02-cheatcodes/send-message-to-l2.md
Labels: size/S

#956 Create empty abi file to prevent mixing build results
  protostar/compiler/compiled_contract_reader_test.py
  protostar/compiler/compiled_contract_writer.py
  protostar/compiler/compiled_contract_writer_test.py
  protostar/compiler/conftest.py
Labels: size/S

#967 Refactor arg types
  docs_generator/reference_docs_generator.py
  protostar/cli/__init__.py
  protostar/cli/arg_type.py
  protostar/cli/arg_type_test.py
  protostar/cli/argument.py
  protostar/cli/argument_parser_facade.py
  protostar/cli/argument_parser_facade_test.py
  protostar/cli/cli_app.py
  protostar/cli/command.py
  protostar/cli/command_test.py
  protostar/cli/protostar_arg_type.py
  protostar/cli/protostar_arg_type_test.py
  protostar/cli/protostar_argument.py
  protostar/cli/protostar_command.py
  protostar/commands/declare_command.py
  protostar/commands/deploy_command.py
  protostar/composition_root.py
  protostar/protostar_cli.py
Labels: size/L

#971 Replaced deprecated network names in docs with new ones
  website/docs/tutorials/06-deploying/01-cli.md
  website/docs/tutorials/06-deploying/02-migrations/call.md
  website/docs/tutorials/06-deploying/02-migrations/invoke.md
Labels: size/XS

#969 Relative path in logged tests
  protostar/commands/test/test_command.py
  protostar/commands/test/test_result_formatter.py
  protostar/commands/test/test_result_formatter_test.py
  protostar/commands/test/testing_live_logger.py
  tests/integration/cheatcodes/send_message_to_l2/send_message_to_l2_test.py
  tests/integration/protostar_fixture.py
Labels: size/S

#950 Reformat & fix typos in `send_message_to_l2` docs
  website/docs/tutorials/07-testing/02-cheatcodes/send-message-to-l2.md
Labels: size/S

#976 Use `ProtostarCommand` and `ProtostarArgument`
  docs_generator/reference_docs_generator.py
  docs_generator/reference_docs_generator_test.py
  protostar/cli/__init__.py
  protostar/cli/argument_parser_facade_test.py
  protostar/cli/cli_app_test.py
  protostar/cli/command.py
  protostar/cli/conftest.py
  protostar/cli/network_command_util.py
  protostar/cli/signable_command_util.py
  protostar/commands/build_command.py
  protostar/commands/cairo_migrate_command.py
  protostar/commands/declare_command.py
  protostar/commands/deploy_command.py
  protostar/commands/format_command.py
  protostar/commands/init/init_command.py
  protostar/commands/install/install_command.py
  protostar/commands/migrate_command.py
  protostar/commands/migrate_configuration_file_command.py
  protostar/commands/remove/remove_command.py
  protostar/commands/test/test_command.py
  protostar/commands/update/update_command.py
  protostar/commands/upgrade_command.py
  protostar/composition_root.py
  protostar/configuration_profile_cli.py
  protostar/protostar_cli.py
  protostar/protostar_cli_test.py
Labels: size/M

#947 Parameterized tests
  protostar/testing/cheatcodes/__init__.py
  protostar/testing/cheatcodes/example_cheatcode.py
  protostar/testing/environments/fuzz_test_execution_environment.py
  protostar/testing/environments/setup_case_execution_environment.py
  protostar/testing/test_case_runners/test_case_runner_factory.py
  protostar/testing/test_config.py
  protostar/testing/test_config_test.py
  tests/integration/fuzzing/fuzzing_test.py
  tests/integration/fuzzing/parameterized_test.cairo
  website/docs/tutorials/07-testing/02-cheatcodes/example.md
  website/docs/tutorials/07-testing/02-cheatcodes/given.md
  website/docs/tutorials/07-testing/02-cheatcodes/max-examples.md
Labels: size/M

#975 Refine init command
  protostar/commands/init/init_command.py
  protostar/commands/init/project_creator/_project_creator.py
  protostar/commands/init/project_creator/adapted_project_creator.py
  protostar/commands/init/project_creator/new_project_creator.py
  tests/e2e/conftest.py
  tests/e2e/test_misc_commands.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/03-project-initialization.md
Labels: size/M

#988 Remove benchmark tests
  pyproject.toml
  tests/benchmarks/basic.cairo
  tests/benchmarks/constants.py
  tests/benchmarks/statistical_test.py
  tests/benchmarks/test_benchmark.py
Labels: chore, size/L

#972 Support for declaring/deploying contract by name in test cheatcodes
  protostar/commands/test/test_command.py
  protostar/compiler/project_compiler.py
  protostar/migrator/migrator_execution_environment.py
  protostar/starknet/execution_state.py
  protostar/testing/cheatcodes/declare_cheatcode.py
  protostar/testing/environments/common_test_cheatcode_factory.py
  protostar/testing/starkware/test_execution_state.py
  protostar/testing/test_case_runners/setup_case_runner.py
  protostar/testing/test_runner.py
  protostar/testing/test_scheduler.py
  tests/integration/cheatcodes/declare/declare_contract_test.cairo
  tests/integration/cheatcodes/declare/declare_contract_test.py
  tests/integration/cheatcodes/declare/declaring_contract_by_name_test.cairo
  tests/integration/cheatcodes/deploy_contract/deploy_contract_test.py
  tests/integration/cheatcodes/deploy_contract/deploying_contract_by_name_test.cairo
  tests/integration/conftest.py
Labels: size/M

#989 Extract `argument_parser` module
  docs_generator/reference_docs_generator.py
  docs_generator/reference_docs_generator_test.py
  protostar/argument_parser/__init__.py
  protostar/argument_parser/arg_type.py
  protostar/argument_parser/arg_type_test.py
  protostar/argument_parser/argument.py
  protostar/argument_parser/argument_parser_facade.py
  protostar/argument_parser/argument_parser_facade_test.py
  protostar/argument_parser/cli_app.py
  protostar/argument_parser/cli_app_test.py
  protostar/argument_parser/command.py
  protostar/argument_parser/config_file_argument_resolver.py
  protostar/argument_parser/conftest.py
  protostar/cli/__init__.py
  protostar/cli/protostar_arg_type.py
  protostar/cli/protostar_argument.py
  protostar/cli/protostar_command.py
  protostar/composition_root.py
  protostar/configuration_file/argument_value_resolver.py
  protostar/configuration_profile_cli.py
  protostar/protostar_cli.py
  protostar/protostar_cli_test.py
  protostar/start.py
Labels: size/S

#878 Profiling
  .github/CODEOWNERS
  protostar/commands/test/test_command.py
  protostar/profiler/__init__.py
  protostar/profiler/contract_profiler.py
  protostar/profiler/contract_profiler_test.py
  protostar/profiler/pprof.py
  protostar/profiler/transaction_profiler.py
  protostar/profiler/transaction_profiler_test.py
  protostar/protostar_cli.py
  protostar/starknet/cheatable_execute_entry_point.py
  protostar/testing/environments/execution_environment.py
  protostar/testing/environments/fuzz_test_execution_environment.py
  protostar/testing/environments/test_execution_environment.py
  protostar/testing/test_config.py
  protostar/testing/test_runner.py
  protostar/testing/test_scheduler.py
  tests/e2e/fixtures/fuzz_test.cairo
  tests/e2e/test_testing.py
  tests/integration/conftest.py
  tests/integration/profile_tests/basic_contract.cairo
  tests/integration/profile_tests/dummy_test.cairo
  tests/integration/profile_tests/example_profile_contract_test.cairo
  tests/integration/profile_tests/profile_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/07-testing/README.md
Labels: size/XXL

#994 Make `deploy_contract` constructor call errors more user-friendly
  protostar/testing/cheatcodes/deploy_cheatcode.py
  protostar/testing/cheatcodes/prepare_cheatcode.py
  tests/integration/cheatcodes/deploy_contract/deploy_contract_test.py
  tests/integration/cheatcodes/deploy_contract/deploying_contract_with_incorrect_args_test.cairo
Labels: size/S

#990 Add Protostar Versioning section
  website/docs/tutorials/02-installation.md
Labels: size/XS

#974 Add `invoke` command
  protostar/commands/__init__.py
  protostar/commands/invoke_command.py
  protostar/composition_root.py
  protostar/migrator/cheatcodes/migrator_invoke_cheatcode.py
  protostar/starknet_gateway/__init__.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/gateway_response.py
  pyproject.toml
  tests/data/contracts.py
  tests/e2e/test_gateway_commands.py
  tests/e2e/test_gateway_commands/contract_with_constructor.cairo
  tests/e2e/test_gateway_commands/protostar_toml_with_constructor_args.toml
  tests/integration/commands/invoke_command_test.py
  tests/integration/conftest.py
  tests/integration/gateway/gateway_facade_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/06-deploying/01-cli.md
Labels: size/L

#980 Update `mock_call` docs
  website/docs/tutorials/07-testing/02-cheatcodes/mock-call.md
Labels: size/XS

#1009 Purge traces of benchmarks from the project
  .github/workflows/checks.yml
  poetry.lock
  pyproject.toml
Labels: chore, size/S

#1010 Update Docusaurus
  website/package.json
  website/yarn.lock
Labels: size/XXL

#984 Docs for Profiling
  website/docs/tutorials/09-profiling.md
  website/docs/tutorials/prof1.png
  website/docs/tutorials/prof2.png
  website/docs/tutorials/prof3.png
Labels: size/S

#979 Unify max-fee interfaces across commands and cheatcodes
  protostar/migrator/cheatcodes/migrator_invoke_cheatcode.py
  protostar/starknet_gateway/gateway_facade.py
  tests/e2e/test_migrating/migration_signed_invokes.cairo
  tests/integration/migrator/migrator_invoke_cheatcode_test.py
  website/docs/tutorials/06-deploying/02-migrations/invoke.md
Labels: size/S

#949 Redesigning `protostar.toml` 11 — Rolling integration — `ProjectCairoPathBuilder`
  protostar/commands/test/test_command.py
  protostar/compiler/project_cairo_path_builder.py
  protostar/composition_root.py
  protostar/configuration_file/__init__.py
  protostar/configuration_file/configuration_file.py
  protostar/configuration_file/configuration_file_factory.py
  protostar/configuration_file/configuration_file_factory_test.py
  protostar/configuration_file/configuration_file_v2.py
  protostar/configuration_file/configuration_file_v2_migrator.py
  protostar/configuration_file/configuration_file_v2_test.py
  protostar/configuration_file/conftest.py
  protostar/configuration_file/fake_configuration_file.py
  protostar/testing/test_runner.py
  protostar/testing/test_scheduler.py
  tests/integration/conftest.py
  tests/integration/project_compiler/project_compiler_test.py
  tests/integration/protostar_fixture.py
Labels: size/M

#1026 Update the `PROTOSTAR_ACCOUNT_PRIVATE_KEY` variable name in the docs
  website/docs/tutorials/06-deploying/01-cli.md
Labels: size/XS

#1027 Fix waiting for declare acceptance with fee errors
  protostar/starknet_gateway/gateway_facade.py
  tests/integration/deploying/declare_command_test.py
Labels: size/S

#1019 Do not lit a fire so much in some cheatcodes docs
  website/docs/tutorials/07-testing/02-cheatcodes/example.md
  website/docs/tutorials/07-testing/02-cheatcodes/given.md
  website/docs/tutorials/07-testing/02-cheatcodes/max-examples.md
Labels: size/XS

#966 Fix store for 0.10.1 cairo-lang
  protostar/testing/cheatcodes/store_cheatcode.py
Labels: size/XS

#1023 Expand documentation on setup hooks
  website/docs/tutorials/07-testing/README.md
Labels: size/S

#1048 Hot-fix stale comments
  website/src/theme/DocPage/Layout/Main/index.js
Labels: size/XS

#1056 Enable git file transport for all unit tests
  .github/workflows/checks.yml
  README.md
Labels: size/XS

#1053 Implement `call` command
  protostar/commands/__init__.py
  protostar/commands/call_command.py
  protostar/composition_root.py
  protostar/starknet_gateway/gateway_facade.py
  tests/integration/commands/call_command_test.py
  tests/integration/commands/getter_contract.cairo
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
Labels: feature, size/M

#1029 Redesigning `protostar.toml` 12 — Rolling integration — `ProjectCompiler`
  protostar/compiler/project_compiler.py
  protostar/composition_root.py
  protostar/configuration_file/configuration_file_factory.py
  protostar/configuration_file/fake_configuration_file.py
  protostar/testing/test_runner.py
  tests/integration/conftest.py
  tests/integration/gateway/gateway_facade_test.py
  tests/integration/project_compiler/project_compiler_test.py
  tests/integration/protostar_fixture.py
Labels: size/M

#1036 Optimize profiler, bump limit
  protostar/profiler/contract_profiler.py
  protostar/testing/test_shared_tests_state.py
Labels: size/S

#981 Suggest adding cairo-path to the protostar.toml after adding a package
  protostar/commands/install/install_command.py
  protostar/configuration_file/configuration_file.py
Labels: size/S

#1035 Set CODEOWNERS for scripting modules
  .github/CODEOWNERS
Labels: size/S

#1077 Disabled invalid-name lint
  .pylintrc
  protostar/profiler/contract_profiler.py
  protostar/profiler/contract_profiler_test.py
  protostar/profiler/pprof.py
  protostar/profiler/transaction_profiler.py
  tests/integration/asserts/asserts_test.py
  tests/integration/conftest.py
Labels: size/XS
