Repository software-mansion/protostar, pull requests merged in 2022-12, with the labels that each got.

#1221 Removed required git version from docs
  website/docs/tutorials/02-installation.md
Labels: size/XS

#1223 Multicall file interpreter
  protostar/commands/deploy_account_command.py
  protostar/starknet_gateway/__init__.py
  protostar/starknet_gateway/account_manager.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/multicall/__init__.py
  protostar/starknet_gateway/multicall/call_resolver.py
  protostar/starknet_gateway/multicall/call_resolver_test.py
  protostar/starknet_gateway/multicall/multicall_file_interpreter.py
  protostar/starknet_gateway/multicall/multicall_file_interpreter_test.py
  protostar/starknet_gateway/multicall/multicall_structs.py
  protostar/starknet_gateway/multicall/multicall_use_case.py
  protostar/starknet_gateway/type.py
  tests/integration/gateway/multicall_use_case_test.py
  tests/integration/protostar_fixture.py
Labels: size/M

#977 Add Uint256 strategy
  protostar/testing/fuzzing/strategies/__init__.py
  protostar/testing/fuzzing/strategies/uint256.py
  protostar/testing/fuzzing/strategy_descriptor.py
  protostar/testing/fuzzing/strategy_inference.py
  protostar/testing/fuzzing/strategy_inference_test.py
  tests/integration/fuzzing_strategies/fuzzing_strategies_test.py
  tests/integration/fuzzing_strategies/uint256_test.cairo
Labels: size/M

#1249 Fix gas estimation
  protostar/starknet/contract.py
  tests/data/contracts.py
  tests/integration/commands/test_command_test.py
Labels: size/S

#1224 Multicall command
  protostar/commands/__init__.py
  protostar/commands/multicall_command.py
  protostar/composition_root.py
  protostar/io/__init__.py
  protostar/io/simple_table.py
  protostar/io/simple_table_test.py
  protostar/starknet_gateway/account_manager.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/multicall/__init__.py
  protostar/starknet_gateway/multicall/multicall_file_example.py
  protostar/starknet_gateway/multicall/multicall_file_interpreter.py
  protostar/starknet_gateway/multicall/multicall_file_interpreter_test.py
  protostar/starknet_gateway/multicall/multicall_structs.py
  tests/e2e/test_gateway_commands.py
  tests/integration/commands/multicall_command_test.py
  tests/integration/gateway/multicall_use_case_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
Labels: size/L

#1255 Revert "Multicall command" to brute fix the CI
  protostar/commands/__init__.py
  protostar/commands/multicall_command.py
  protostar/composition_root.py
  protostar/io/__init__.py
  protostar/io/simple_table.py
  protostar/io/simple_table_test.py
  protostar/starknet_gateway/account_manager.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/multicall/__init__.py
  protostar/starknet_gateway/multicall/multicall_file_example.py
  protostar/starknet_gateway/multicall/multicall_file_interpreter.py
  protostar/starknet_gateway/multicall/multicall_file_interpreter_test.py
  protostar/starknet_gateway/multicall/multicall_structs.py
  tests/e2e/test_gateway_commands.py
  tests/integration/commands/multicall_command_test.py
  tests/integration/gateway/multicall_use_case_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
Labels: size/L

#1227 Multicall docs
  website/docs/tutorials/08-interacting-with-starknet/07-multicall.md
Labels: size/S

#1263 Hotfix — make `TestCache` tests independent
  tests/integration/testing_cache/test_cache.py
Labels: size/XS

#1244 Calculate class hashes when building
  protostar/commands/build_command.py
  protostar/compiler/project_compiler.py
  tests/e2e/test_building.py
  website/docs/cli-reference.md
Labels: size/S

#1265 Added `UInt256` fuzzing docs
  website/docs/tutorials/07-testing/03-fuzzing/strategies.md
Labels: size/S

#1274 Fix flaky test (`empty_protostar_toml` fixture)
  tests/integration/conftest.py
Labels: size/S

#1273 Revert commit "release Protostar 0.9.0" (release failed)
  pyproject.toml
Labels: size/XS

#1272 Fix building on MacOS. Add new PR check.
  .github/workflows/build_binaries.yml
  .github/workflows/builds_on_mac.yml
  .github/workflows/checks.yml
Labels: size/S

#1248 Added uint256 as input test
  protostar/starknet_gateway/gateway_facade.py
  tests/data/contracts.py
  tests/integration/gateway/uint256_as_input_test.py
Labels: size/M

#1264 Accept private key as int
  protostar/cli/signable_command_util.py
Labels: size/XS

#1286 Hotfix CI freezes — Use `module` scope for devnet fixture
  tests/conftest.py
  tests/e2e/conftest.py
  tests/integration/conftest.py
Labels: size/S

#1278 Pure cairo VM testing
  protostar/commands/test/test_command.py
  protostar/starknet/compiler/cairo_compilation.py
  protostar/starknet/compiler/cairo_compilation_test.py
  protostar/starknet/compiler/common.py
  protostar/starknet/compiler/examples/array_sum_external_test.cairo
  protostar/starknet/compiler/examples/array_sum_test.cairo
  protostar/starknet/compiler/pass_managers.py
  protostar/starknet/compiler/starknet_compilation.py
  protostar/testing/cairo_test_runner.py
  protostar/testing/starkware/cairo_test_execution_state.py
  protostar/testing/test_case_runners/cairo_test_case_runner.py
  protostar/testing/test_collector.py
  protostar/testing/test_collector_test.py
  tests/integration/asserts/asserts_test.py
  tests/integration/cheatcodes/assume_and_reject/assume_and_reject_test.py
  tests/integration/cheatcodes/declare/declare_contract_test.py
  tests/integration/cheatcodes/declare_contract/disabling_hint_validation_test.py
  tests/integration/cheatcodes/deploy_contract/deploy_contract_test.py
  tests/integration/cheatcodes/expect_call/expect_call_test.py
  tests/integration/cheatcodes/expect_events/expect_events_test.py
  tests/integration/cheatcodes/expect_revert/expect_revert_test.py
  tests/integration/cheatcodes/load/load_test.py
  tests/integration/cheatcodes/mock_call/mock_call_test.py
  tests/integration/cheatcodes/prank/prank_test.py
  tests/integration/cheatcodes/prepare/prepare_test.py
  tests/integration/cheatcodes/reflect/reflect_test.py
  tests/integration/cheatcodes/roll/roll_test.py
  tests/integration/cheatcodes/send_message_to_l2/send_message_to_l2_test.py
  tests/integration/cheatcodes/skip/skip_test.py
  tests/integration/cheatcodes/store/store_test.py
  tests/integration/cheatcodes/warp/warp_test.py
  tests/integration/conftest.py
  tests/integration/constructor_in_tested_file/constructor_in_tested_file_test.py
  tests/integration/fuzzing/fuzzing_test.py
  tests/integration/fuzzing_strategies/fuzzing_strategies_test.py
  tests/integration/profile_tests/profile_test.py
  tests/integration/pure_cairo_vm/conftest.py
  tests/integration/pure_cairo_vm/library.cairo
  tests/integration/pure_cairo_vm/pure_cairo_broken_test.cairo
  tests/integration/pure_cairo_vm/pure_cairo_test.cairo
  tests/integration/pure_cairo_vm/test_pure_cairo_vm.py
  tests/integration/testing_hooks/testing_hooks_test.py
  tests/integration/testing_output/testing_output_test.py
  tests/integration/testing_steps/testing_steps_test.py
  tests/integration/testing_timing/testing_timing_test.py
Labels: size/XL

#1279 Prevent using felt pointer for dict
  protostar/starknet/data_transformer.py
  tests/integration/data_transformer/contracts.py
  tests/integration/data_transformer/data_transformer_test.py
Labels: size/S

#1275 Fix `--inputs` 1 — `call` command
  protostar/commands/__init__.py
  protostar/commands/call/__init__.py
  protostar/commands/call/call_command.py
  protostar/commands/call/call_command_messages.py
  protostar/starknet/__init__.py
  protostar/starknet_gateway/__init__.py
  protostar/starknet_gateway/abi_resolver.py
  protostar/starknet_gateway/call/__init__.py
  protostar/starknet_gateway/call/call_structs.py
  protostar/starknet_gateway/call/call_use_case.py
  protostar/starknet_gateway/gateway_facade.py
  tests/data/contracts.py
  tests/e2e/test_gateway_commands.py
  tests/integration/commands/call_command_test.py
  tests/integration/commands/invoke_command_test.py
  tests/integration/commands/multicall_command_test.py
  tests/integration/gateway/multicall_use_case_test.py
  tests/integration/gateway/uint256_as_input_test.py
  tests/integration/protostar_fixture.py
Labels: size/M

#1292 Lint everything
  .pylintrc
  binary_entrypoint.py
  docs_generator/reference_docs_generator.py
  protostar/starknet/compiler/__init__.py
  protostar/starknet/compiler/cairo_compilation.py
  protostar/starknet/compiler/pass_managers.py
  pyproject.toml
  tests/conftest.py
  tests/e2e/conftest.py
  tests/e2e/test_building.py
  tests/e2e/test_formatting.py
  tests/e2e/test_fuzzing.py
  tests/e2e/test_misc_commands.py
  tests/integration/cheatcodes/expect_call/expect_call_test.py
  tests/integration/compilation/starknet_compilation_test.py
  tests/integration/compilation/test_case_compiler_test.py
  tests/integration/fuzzing_strategies/fuzzing_strategies_test.py
  tests/integration/gateway/gateway_facade_test.py
  tests/integration/gateway/uint256_as_input_test.py
  tests/integration/protostar_fixture.py
  tests/integration/testing_cache/test_cache.py
  tests/integration/testing_timing/testing_timing_test.py
Labels: size/M

#1289 Fix `--inputs` 2 — `invoke` command
  protostar/commands/__init__.py
  protostar/commands/call/call_command.py
  protostar/commands/invoke/__init__.py
  protostar/commands/invoke/invoke_command.py
  protostar/commands/invoke/messages.py
  protostar/commands/multicall_command.py
  protostar/starknet/__init__.py
  protostar/starknet/types.py
  protostar/starknet_gateway/__init__.py
  protostar/starknet_gateway/account_manager.py
  protostar/starknet_gateway/call/__init__.py
  protostar/starknet_gateway/call/call_structs.py
  protostar/starknet_gateway/call/call_use_case.py
  protostar/starknet_gateway/core/__init__.py
  protostar/starknet_gateway/core/structs.py
  protostar/starknet_gateway/core/types.py
  protostar/starknet_gateway/data_transformer_policy.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/invoke/__init__.py
  protostar/starknet_gateway/invoke/invoke_structs.py
  protostar/starknet_gateway/invoke/invoke_use_case.py
  protostar/starknet_gateway/multicall/__init__.py
  pyproject.toml
  tests/data/contracts.py
  tests/e2e/test_gateway_commands.py
  tests/integration/commands/invoke_command_test.py
  tests/integration/gateway/multicall_use_case_test.py
  tests/integration/protostar_fixture.py
Labels: size/L

#1297 Bring back black profile to isort
  pyproject.toml
Labels: size/XS

#1295 Improve git hooks
  README.md
  pre-commit
  pre-push
  pyproject.toml
  scripts/apply_hooks.sh
  scripts/get_code_check_paths.sh
  scripts/run_format_check.sh
  scripts/run_lint.sh
Labels: size/S

#1242 Add docs for json flag
  protostar/cli/messenger_factory.py
  website/docs/cli-reference.md
  website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
  website/docs/tutorials/08-interacting-with-starknet/02-call.md
  website/docs/tutorials/08-interacting-with-starknet/03-declare.md
  website/docs/tutorials/08-interacting-with-starknet/04-deploy.md
  website/docs/tutorials/08-interacting-with-starknet/scripting.md
Labels: size/M

#1296 Fix undeployed account error message
  protostar/commands/deploy_command.py
  protostar/starknet_gateway/gateway_facade.py
Labels: size/S
