Repository software-mansion/protostar, pull requests merged in 2022-11, with the labels that each got.

#1082 Suggest chain-ids values
  protostar/cli/network_command_util.py
  protostar/cli/network_command_util_test.py
Labels: size/S

#995 Unify parameterize api
  protostar/testing/environments/fuzz_test_execution_environment.py
  tests/integration/fuzzing/fuzzing_test.py
  tests/integration/fuzzing/parameterized_test.cairo
  website/docs/tutorials/07-testing/02-cheatcodes/given.md
  website/docs/tutorials/07-testing/03-fuzzing/README.md
  website/docs/tutorials/07-testing/03-fuzzing/strategies.md
Labels: size/M

#1058 Redesigning `protostar.toml` 13 — Rolling integration — Package management commands
  protostar/cli/__init__.py
  protostar/cli/common_arguments.py
  protostar/cli/lib_path_resolver.py
  protostar/cli/lib_path_resolver_test.py
  protostar/commands/install/install_command.py
  protostar/commands/remove/remove_command.py
  protostar/commands/update/update_command.py
  protostar/compiler/project_cairo_path_builder.py
  protostar/composition_root.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
Labels: size/M

#1073 Redesigning `protostar.toml` 15 — Remove old module
  .github/CODEOWNERS
  protostar/protostar_toml/__init__.py
  protostar/protostar_toml/conftest.py
  protostar/protostar_toml/io/protostar_toml_reader.py
  protostar/protostar_toml/io/protostar_toml_reader_test.py
  protostar/protostar_toml/io/protostar_toml_reader_test/protostar.toml
  protostar/protostar_toml/io/protostar_toml_writer.py
  protostar/protostar_toml/io/protostar_toml_writer_test.py
  protostar/protostar_toml/protostar_config_section.py
  protostar/protostar_toml/protostar_config_section_test.py
  protostar/protostar_toml/protostar_contracts_section.py
  protostar/protostar_toml/protostar_contracts_section_test.py
  protostar/protostar_toml/protostar_project_section.py
  protostar/protostar_toml/protostar_project_section_test.py
  protostar/protostar_toml/protostar_toml_exceptions.py
  protostar/protostar_toml/protostar_toml_exceptions_test.py
  protostar/protostar_toml/protostar_toml_section.py
  tests/integration/protostar_toml/protostar_toml_test.py
Labels: size/XL

#1080 Remove rollback from migrations
  protostar/commands/migrate_command.py
  protostar/commands/migrate_command_test.py
  protostar/migrator/migrator.py
  tests/integration/migrator/migrator_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/06-deploying/02-migrations/README.md
Labels: size/S

#1075 Redesigning `protostar.toml` 16 — Remove `ProtostarVersionProvider`
  protostar/commands/__init__.py
  protostar/composition_root.py
  protostar/configuration_file/configuration_file_v2_migrator.py
  protostar/configuration_file/configuration_file_v2_migrator_test.py
  protostar/self/__init__.py
  protostar/self/conftest.py
  protostar/self/protostar_compatibility_with_project_checker.py
  protostar/self/protostar_compatibility_with_project_checker_test.py
  protostar/self/protostar_directory.py
Labels: size/S

#1020 [0.10.1] Cairo 0.10.1 integration
  poetry.lock
  protostar/starknet/cheatable_cairo_function_runner.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/testing/cheatcodes/store_cheatcode.py
  pyproject.toml
  tests/integration/deploying/declare_command_test.py
Labels: size/S

#1064 Add "address" argument type
  protostar/cli/protostar_arg_type.py
  protostar/cli/protostar_arg_type_test.py
  protostar/cli/signable_command_util.py
  protostar/commands/call_command.py
  protostar/commands/invoke_command.py
  website/docs/cli-reference.md
Labels: enhancement, size/S

#1051 Use `encode_shortstring` function from Starknet.py instead of custom code
  protostar/testing/fuzzing/strategies/short_strings.py
Labels: refactor, size/XS

#1055 [-> 0.10.1] Add `deploy_account` method to the `GatewayFacade`
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/gateway_response.py
  tests/__init__.py
  tests/_conftest/compiled_account/__init__.py
  tests/_conftest/compiled_account/account_contract_with_validate_deploy.cairo
  tests/_conftest/compiled_account/compiled_account.py
  tests/_conftest/devnet/__init__.py
  tests/_conftest/devnet/devnet_account.py
  tests/_conftest/devnet/devnet_account_preparator.py
  tests/_conftest/devnet/devnet_fixture.py
  tests/_conftest/devnet/faucet_contract.py
  tests/conftest.py
  tests/integration/gateway/gateway_facade_test.py
  tests/integration/protostar_fixture.py
Labels: size/L

#1083 Add `deploy-account` command
  protostar/cli/network_command_util.py
  protostar/cli/protostar_arg_type.py
  protostar/cli/protostar_arg_type_test.py
  protostar/cli/signable_command_util.py
  protostar/commands/__init__.py
  protostar/commands/deploy_account_command.py
  protostar/composition_root.py
  tests/_conftest/devnet/devnet_fixture.py
  tests/e2e/test_gateway_commands.py
  tests/integration/commands/deploy_account_command_test.py
  tests/integration/commands/invoke_command_test.py
  tests/integration/gateway/gateway_facade_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
Labels: size/L

#1076 Redesigning `protostar.toml` 17 — Connect `migrate-configuration-file` command
  protostar/commands/migrate_configuration_file_command.py
  protostar/composition_root.py
  protostar/configuration_profile_cli.py
  protostar/protostar_cli.py
  protostar/protostar_cli_test.py
  tests/e2e/test_misc_commands.py
  website/docs/cli-reference.md
Labels: size/M

#1081 Redesigning `protostar.toml` 18 — Connect compatibility checker
  protostar/composition_root.py
  protostar/protostar_cli.py
  protostar/protostar_cli_test.py
  protostar/self/__init__.py
  protostar/self/conftest.py
  protostar/self/protostar_compatibility_with_project_checker.py
  protostar/self/protostar_compatibility_with_project_checker_test.py
Labels: size/M

#1072 Make all cheatcodes use one shared `internal_calls`. Fix `send_message_to_l2` cheatcode.
  protostar/migrator/migrator_cheatcodes_factory.py
  protostar/starknet/cheatable_execute_entry_point.py
  protostar/starknet/cheatcode.py
  protostar/starknet/cheatcode_factory.py
  protostar/testing/cheatcodes/deploy_cheatcode.py
  protostar/testing/environments/common_test_cheatcode_factory.py
  protostar/testing/environments/fuzz_test_execution_environment.py
  protostar/testing/environments/setup_case_execution_environment.py
  protostar/testing/environments/setup_execution_environment.py
  protostar/testing/environments/test_execution_environment.py
  tests/integration/cheatcodes/send_message_to_l2/external_contract_with_l1_handler.cairo
  tests/integration/cheatcodes/send_message_to_l2/send_message_to_l2_test.py
  tests/integration/cheatcodes/send_message_to_l2/simple_l1_handler_test.cairo
Labels: size/M

#1078 Redesigning `protostar.toml` 19 — Docs
  website/docs/tutorials/01-introduction.md
  website/docs/tutorials/03-project-initialization.md
  website/docs/tutorials/04-configuration-file.md
  website/docs/tutorials/05-compiling.md
  website/docs/tutorials/06-dependencies-management.md
  website/docs/tutorials/07-deploying/01-cli.md
  website/docs/tutorials/07-deploying/02-migrations/README.md
  website/docs/tutorials/07-deploying/02-migrations/_category_.yaml
  website/docs/tutorials/07-deploying/02-migrations/call.md
  website/docs/tutorials/07-deploying/02-migrations/declare.md
  website/docs/tutorials/07-deploying/02-migrations/deploy-contract.md
  website/docs/tutorials/07-deploying/02-migrations/invoke.md
  website/docs/tutorials/07-deploying/03-network-config.md
  website/docs/tutorials/07-deploying/README.md
  website/docs/tutorials/07-deploying/_category_.yaml
  website/docs/tutorials/08-testing/01-deploying-contracts.md
  website/docs/tutorials/08-testing/02-cheatcodes/README.md
  website/docs/tutorials/08-testing/02-cheatcodes/_category_.yaml
  website/docs/tutorials/08-testing/02-cheatcodes/assume.md
  website/docs/tutorials/08-testing/02-cheatcodes/declare.md
  website/docs/tutorials/08-testing/02-cheatcodes/deploy-contract.md
  website/docs/tutorials/08-testing/02-cheatcodes/deploy.md
  website/docs/tutorials/08-testing/02-cheatcodes/example.md
  website/docs/tutorials/08-testing/02-cheatcodes/expect-events.md
  website/docs/tutorials/08-testing/02-cheatcodes/expect-revert.md
  website/docs/tutorials/08-testing/02-cheatcodes/given.md
  website/docs/tutorials/08-testing/02-cheatcodes/load.md
  website/docs/tutorials/08-testing/02-cheatcodes/max-examples.md
  website/docs/tutorials/08-testing/02-cheatcodes/mock-call.md
  website/docs/tutorials/08-testing/02-cheatcodes/prepare.md
  website/docs/tutorials/08-testing/02-cheatcodes/reflect.md
  website/docs/tutorials/08-testing/02-cheatcodes/reject.md
  website/docs/tutorials/08-testing/02-cheatcodes/roll.md
  website/docs/tutorials/08-testing/02-cheatcodes/send-message-to-l2.md
  website/docs/tutorials/08-testing/02-cheatcodes/skip.md
  website/docs/tutorials/08-testing/02-cheatcodes/start-prank.md
  website/docs/tutorials/08-testing/02-cheatcodes/store.md
  website/docs/tutorials/08-testing/02-cheatcodes/strategy.md
  website/docs/tutorials/08-testing/02-cheatcodes/warp.md
  website/docs/tutorials/08-testing/03-fuzzing/README.md
  website/docs/tutorials/08-testing/03-fuzzing/_category_.yaml
  website/docs/tutorials/08-testing/03-fuzzing/reproducing-failures.md
  website/docs/tutorials/08-testing/03-fuzzing/strategies.md
  website/docs/tutorials/08-testing/README.md
  website/docs/tutorials/08-testing/_category_.yaml
  website/docs/tutorials/09-formatting.md
  website/docs/tutorials/10-profiling.md
Labels: size/M

#1063 Add "Interacting with StarkNet" docs
  website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
  website/docs/tutorials/08-interacting-with-starknet/02-call.md
  website/docs/tutorials/08-interacting-with-starknet/README.md
  website/docs/tutorials/08-interacting-with-starknet/_category_.yaml
Labels: documentation, size/S

#1112 Revert #1035: CODEOWNERS changes related to scripting
  .github/CODEOWNERS
Labels: size/XS

#1105 Add `deploy-account` doc
  website/docs/tutorials/08-interacting-with-starknet/03-deploy-account.md
Labels: size/S

#1115 Reorder documentation sections
  website/docs/tutorials/01-introduction.md
  website/docs/tutorials/05-compiling.md
  website/docs/tutorials/07-testing/01-deploying-contracts.md
  website/docs/tutorials/07-testing/02-cheatcodes/README.md
  website/docs/tutorials/07-testing/02-cheatcodes/_category_.yaml
  website/docs/tutorials/07-testing/02-cheatcodes/assume.md
  website/docs/tutorials/07-testing/02-cheatcodes/declare.md
  website/docs/tutorials/07-testing/02-cheatcodes/deploy-contract.md
  website/docs/tutorials/07-testing/02-cheatcodes/deploy.md
  website/docs/tutorials/07-testing/02-cheatcodes/example.md
  website/docs/tutorials/07-testing/02-cheatcodes/expect-events.md
  website/docs/tutorials/07-testing/02-cheatcodes/expect-revert.md
  website/docs/tutorials/07-testing/02-cheatcodes/given.md
  website/docs/tutorials/07-testing/02-cheatcodes/load.md
  website/docs/tutorials/07-testing/02-cheatcodes/max-examples.md
  website/docs/tutorials/07-testing/02-cheatcodes/mock-call.md
  website/docs/tutorials/07-testing/02-cheatcodes/prepare.md
  website/docs/tutorials/07-testing/02-cheatcodes/reflect.md
  website/docs/tutorials/07-testing/02-cheatcodes/reject.md
  website/docs/tutorials/07-testing/02-cheatcodes/roll.md
  website/docs/tutorials/07-testing/02-cheatcodes/send-message-to-l2.md
  website/docs/tutorials/07-testing/02-cheatcodes/skip.md
  website/docs/tutorials/07-testing/02-cheatcodes/start-prank.md
  website/docs/tutorials/07-testing/02-cheatcodes/store.md
  website/docs/tutorials/07-testing/02-cheatcodes/strategy.md
  website/docs/tutorials/07-testing/02-cheatcodes/warp.md
  website/docs/tutorials/07-testing/03-fuzzing/README.md
  website/docs/tutorials/07-testing/03-fuzzing/_category_.yaml
  website/docs/tutorials/07-testing/03-fuzzing/reproducing-failures.md
  website/docs/tutorials/07-testing/03-fuzzing/strategies.md
  website/docs/tutorials/07-testing/README.md
  website/docs/tutorials/07-testing/_category_.yaml
  website/docs/tutorials/08-deploying/01-cli.md
  website/docs/tutorials/08-deploying/02-migrations/README.md
  website/docs/tutorials/08-deploying/02-migrations/_category_.yaml
  website/docs/tutorials/08-deploying/02-migrations/call.md
  website/docs/tutorials/08-deploying/02-migrations/declare.md
  website/docs/tutorials/08-deploying/02-migrations/deploy-contract.md
  website/docs/tutorials/08-deploying/02-migrations/invoke.md
  website/docs/tutorials/08-deploying/03-network-config.md
  website/docs/tutorials/08-deploying/README.md
  website/docs/tutorials/08-deploying/_category_.yaml
  website/docs/tutorials/09-interacting-with-starknet/01-invoke.md
  website/docs/tutorials/09-interacting-with-starknet/02-call.md
  website/docs/tutorials/09-interacting-with-starknet/03-deploy-account.md
  website/docs/tutorials/09-interacting-with-starknet/README.md
  website/docs/tutorials/09-interacting-with-starknet/_category_.yaml
  website/docs/tutorials/10-formatting.md
  website/docs/tutorials/11-profiling.md
Labels: size/S

#1120 Disable alphabetical sort in the isort configuration
  pyproject.toml
Labels: size/XS

#1060 Add `expect_call` cheatcode
  protostar/starknet/cheatable_cached_state.py
  protostar/starknet/cheatable_syscall_handler.py
  protostar/testing/cheatcodes/__init__.py
  protostar/testing/cheatcodes/expect_call_cheatcode.py
  protostar/testing/environments/test_execution_environment.py
  protostar/testing/test_environment_exceptions.py
  protostar/testing/test_environment_exceptions_test.py
  tests/integration/cheatcodes/expect_call/basic_contract.cairo
  tests/integration/cheatcodes/expect_call/expect_call_test.cairo
  tests/integration/cheatcodes/expect_call/expect_call_test.py
  website/docs/tutorials/08-testing/02-cheatcodes/expect-call.md
Labels: size/M

#1117 Deprecate migrations in documentation
  website/docs/tutorials/08-deploying/02-migrations/README.md
  website/docs/tutorials/08-deploying/02-migrations/_category_.yaml
Labels: size/S

#1119 Warn users of migrations about their future deletion
  protostar/commands/migrate_command.py
Labels: size/S

#1138 Hotfix testing docs
  website/docs/tutorials/07-testing/02-cheatcodes/expect-call.md
Labels: size/XS

#1130 Remove legacy network names
  protostar/cli/network_command_util.py
  protostar/cli/network_command_util_test.py
  protostar/commands/deploy_command.py
  protostar/starknet_gateway/network_config.py
  protostar/starknet_gateway/network_config_test.py
  website/docs/cli-reference.md
Labels: size/S

#1121 Move `declare` and `deploy` command docs to "Interacting with StarkNet"
  website/docs/tutorials/01-introduction.md
  website/docs/tutorials/07-testing/02-cheatcodes/declare.md
  website/docs/tutorials/07-testing/02-cheatcodes/deploy-contract.md
  website/docs/tutorials/07-testing/02-cheatcodes/expect-call.md
  website/docs/tutorials/08-deploying/01-cli.md
  website/docs/tutorials/08-deploying/README.md
  website/docs/tutorials/08-deploying/_category_.yaml
  website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
  website/docs/tutorials/08-interacting-with-starknet/02-call.md
  website/docs/tutorials/08-interacting-with-starknet/03-declare.md
  website/docs/tutorials/08-interacting-with-starknet/04-deploy.md
  website/docs/tutorials/08-interacting-with-starknet/05-deploy-account.md
  website/docs/tutorials/08-interacting-with-starknet/06-signing.md
  website/docs/tutorials/08-interacting-with-starknet/README.md
  website/docs/tutorials/08-interacting-with-starknet/_category_.yaml
  website/docs/tutorials/09-interacting-with-starknet/README.md
  website/docs/tutorials/09-migrations/README.md
  website/docs/tutorials/09-migrations/call.md
  website/docs/tutorials/09-migrations/declare.md
  website/docs/tutorials/09-migrations/deploy-contract.md
  website/docs/tutorials/09-migrations/invoke.md
  website/docs/tutorials/09-migrations/network-config.md
  website/docusaurus.config.js
Labels: size/M

#1135 Remove unnecessary execution time logs from documentation
  website/docs/tutorials/07-testing/03-fuzzing/README.md
  website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
  website/docs/tutorials/08-interacting-with-starknet/02-call.md
Labels: size/S

#1136 Allow E2E testing without stderr, and do not emit empty lines by disa…
  binary_entrypoint.py
  protostar/cli/activity_indicator.py
  tests/e2e/conftest.py
Labels: size/S

#1134 Do not bundle GitPython with Protostar
  binary_entrypoint.py
  poetry.lock
  pyproject.toml
Labels: size/S

#1144 Remove code coverage from the project
  .github/workflows/checks.yml
  CONTRIBUTING.md
  codecov.yml
  poetry.lock
  pyproject.toml
Labels: size/S

#1141 Use pytest-xdist to further parallelize tests
  poetry.lock
  pyproject.toml
Labels: size/XS

#1122 Block explorer links
  protostar/cli/common_arguments.py
  protostar/cli/protostar_arg_type.py
  protostar/cli/protostar_arg_type_test.py
  protostar/commands/declare_command.py
  protostar/commands/declare_command_test.py
  protostar/commands/deploy_command.py
  protostar/commands/deploy_command_test.py
  protostar/commands/invoke_command.py
  protostar/starknet_gateway/__init__.py
  protostar/starknet_gateway/block_explorer/__init__.py
  protostar/starknet_gateway/block_explorer/block_explorer.py
  protostar/starknet_gateway/block_explorer/block_explorer_factory.py
  protostar/starknet_gateway/block_explorer/fake_block_explorer.py
  protostar/starknet_gateway/block_explorer/stark_scan_block_explorer.py
  protostar/starknet_gateway/block_explorer/viewblock_block_explorer.py
  protostar/starknet_gateway/block_explorer/voyager_block_explorer.py
  protostar/starknet_gateway/gateway_response.py
  protostar/starknet_gateway/gateway_response_test.py
  protostar/starknet_gateway/network_config.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
Labels: size/L

#1147 Show StarkScan and Voyager links by default
  protostar/cli/common_arguments.py
  protostar/starknet_gateway/block_explorer/block_explorer.py
  protostar/starknet_gateway/block_explorer/block_explorer_factory.py
  protostar/starknet_gateway/block_explorer/combined_block_explorer.py
  protostar/starknet_gateway/block_explorer/fake_block_explorer.py
  protostar/starknet_gateway/block_explorer/stark_scan_block_explorer.py
  protostar/starknet_gateway/block_explorer/viewblock_block_explorer.py
  protostar/starknet_gateway/block_explorer/voyager_block_explorer.py
  website/docs/cli-reference.md
Labels: size/M

#1145 Add `data-transformer` usage example in expect-events docs
  website/docs/tutorials/07-testing/02-cheatcodes/expect-events.md
Labels: documentation, size/S

#1131 Set up output formatting infrastructure
  protostar/cli/__init__.py
  protostar/cli/messenger_factory.py
  protostar/io/__init__.py
  protostar/io/output.py
Labels: size/S

#1153 Remove max returns
  .pylintrc
Labels: size/XS

#1137 Implement structured output for `call` command
  protostar/commands/call_command.py
  protostar/composition_root.py
  tests/e2e/test_gateway_commands.py
  tests/integration/commands/call_command_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/08-interacting-with-starknet/02-call.md
Labels: size/M

#1132 Implement structured output for `format` command
  protostar/commands/format_command.py
  protostar/composition_root.py
  protostar/formatter/formatter.py
  protostar/formatter/formatting_result.py
  protostar/formatter/formatting_result_test.py
  protostar/formatter/formatting_summary.py
  protostar/formatter/formatting_summary_test.py
  tests/integration/formatter/formatter_test.py
  tests/integration/protostar_fixture.py
Labels: size/L

#1157 Profile builtins
  protostar/profiler/contract_profiler.py
  protostar/profiler/pprof.py
  protostar/profiler/transaction_profiler.py
  protostar/profiler/transaction_profiler_test.py
  protostar/starknet/cheatable_execute_entry_point.py
  tests/integration/profile_tests/example_profile_contract_test.cairo
  tests/integration/profile_tests/profile_test.py
  website/docs/tutorials/11-profiling.md
Labels: size/M

#1159 Bump Starknet.py
  poetry.lock
  pyproject.toml
Labels: size/XS

#1146 Support indicators in structured output and implement one for `build`…
  protostar/cli/messenger_factory.py
  protostar/commands/build_command.py
  protostar/composition_root.py
  protostar/io/output.py
  tests/integration/protostar_fixture.py
Labels: size/M

#1150 Add `calculate-account-address` command
  protostar/cli/common_arguments.py
  protostar/commands/__init__.py
  protostar/commands/calculate_account_address_command.py
  protostar/commands/deploy_account_command.py
  protostar/composition_root.py
  protostar/starknet/account_address.py
  protostar/starknet/account_address_test.py
  protostar/starknet/address.py
  protostar/starknet/address_test.py
  tests/_conftest/devnet/devnet_account_preparator.py
  tests/e2e/test_gateway_commands.py
  tests/integration/commands/calculate_contract_address_command_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/08-interacting-with-starknet/05-deploy-account.md
Labels: size/M

#1167 Remove unnecessary `@pytest.mark.asyncio` markers from tests
  protostar/argument_parser/cli_app_test.py
  protostar/testing/hook_test.py
  tests/integration/asserts/asserts_test.py
  tests/integration/cheatcodes/declare/declare_contract_test.py
  tests/integration/cheatcodes/deploy_contract/deploy_contract_test.py
  tests/integration/cheatcodes/expect_events/expect_events_test.py
  tests/integration/cheatcodes/load/load_test.py
  tests/integration/cheatcodes/mock_call/mock_call_test.py
  tests/integration/cheatcodes/prank/prank_test.py
  tests/integration/constructor_in_tested_file/constructor_in_tested_file_test.py
  tests/integration/testing_output/testing_output_test.py
Labels: chore, size/S

#1154 Implement structured output for `invoke` command
  protostar/commands/invoke_command.py
  protostar/composition_root.py
  tests/e2e/test_gateway_commands.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
Labels: size/M

#1165 Make `test_deploying_and_interacting_with_contract` more focused on s…
  poetry.lock
  pyproject.toml
  tests/e2e/test_gateway_commands.py
Labels: size/S

#1166 Implement structured output for `declare` command
  protostar/commands/declare_command.py
  protostar/commands/declare_command_test.py
  protostar/composition_root.py
  tests/e2e/test_gateway_commands.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/08-interacting-with-starknet/03-declare.md
Labels: size/M

#1160 Implement structured output for `deploy-account` command
  protostar/commands/deploy_account_command.py
  protostar/composition_root.py
  protostar/starknet_gateway/gateway_facade.py
  tests/e2e/test_gateway_commands.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
Labels: size/S

#1169 Use global `logging` instead of passing `Logger` as dependency
  protostar/cli/network_command_util.py
  protostar/cli/network_command_util_test.py
  protostar/cli/signable_command_util.py
  protostar/cli/signable_command_util_test.py
  protostar/commands/cairo_migrate_command.py
  protostar/commands/call_command.py
  protostar/commands/declare_command.py
  protostar/commands/deploy_account_command.py
  protostar/commands/deploy_command.py
  protostar/commands/install/install_command.py
  protostar/commands/invoke_command.py
  protostar/commands/migrate_command.py
  protostar/commands/migrate_configuration_file_command.py
  protostar/commands/remove/remove_command.py
  protostar/commands/test/test_command.py
  protostar/commands/test/test_command_cache.py
  protostar/commands/test/testing_live_logger.py
  protostar/commands/update/update_command.py
  protostar/commands/upgrade_command.py
  protostar/composition_root.py
  protostar/migrator/cheatcodes/migrator_invoke_cheatcode.py
  protostar/protostar_cli.py
  protostar/protostar_cli_test.py
  protostar/self/protostar_directory.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/gateway_facade_factory.py
  protostar/testing/environments/fuzz_test_execution_environment.py
  protostar/testing/testing_summary.py
  protostar/upgrader/latest_version_checker.py
  protostar/upgrader/latest_version_checker_test.py
  protostar/upgrader/upgrade_manager.py
  tests/integration/conftest.py
  tests/integration/protostar_fixture.py
Labels: size/L

#941 Fix calling/invoking through proxies
  protostar/compiler/compiled_contract_reader.py
  protostar/starknet_gateway/__init__.py
  protostar/starknet_gateway/contract_function_factory.py
  protostar/starknet_gateway/gateway_facade.py
  tests/conftest.py
  tests/data/contracts.py
  tests/data/oz_proxy_compiled_contract.json
  tests/integration/gateway/gateway_facade_test.py
Labels: size/M

#1173 Fix kebab-case with positional arguments
  .pylintrc
  protostar/argument_parser/argument_parser_facade.py
  protostar/argument_parser/argument_parser_facade_test.py
Labels: size/S

#1168 Support deploy with UDC in `deploy` command
  poetry.lock
  protostar/commands/deploy_command.py
  protostar/migrator/cheatcodes/migrator_deploy_contract_cheatcode.py
  protostar/starknet_gateway/gateway_facade.py
  pyproject.toml
  tests/e2e/test_gateway_commands.py
  tests/integration/commands/call_command_test.py
  tests/integration/commands/invoke_command_test.py
  tests/integration/deploying/deploy_command_test.py
  tests/integration/gateway/gateway_facade_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
Labels: size/L

#1174 Deploy structured output
  protostar/commands/deploy_command.py
  protostar/commands/deploy_command_test.py
  protostar/composition_root.py
  tests/e2e/test_gateway_commands.py
  tests/integration/protostar_fixture.py
Labels: size/M

#1170 Integrate `Address` value object
  protostar/cli/protostar_arg_type.py
  protostar/cli/signable_command_util.py
  protostar/cli/signable_command_util_test.py
  protostar/commands/calculate_account_address_command.py
  protostar/commands/call_command.py
  protostar/commands/declare_command.py
  protostar/commands/deploy_account_command.py
  protostar/commands/deploy_command.py
  protostar/commands/deploy_command_test.py
  protostar/commands/invoke_command.py
  protostar/migrator/cheatcodes/migrator_call_cheatcode.py
  protostar/migrator/cheatcodes/migrator_declare_cheatcode.py
  protostar/migrator/cheatcodes/migrator_deploy_contract_cheatcode.py
  protostar/migrator/cheatcodes/migrator_invoke_cheatcode.py
  protostar/migrator/migrator_cheatcodes_factory.py
  protostar/starknet/__init__.py
  protostar/starknet/account_address.py
  protostar/starknet/account_address_test.py
  protostar/starknet/address.py
  protostar/starknet/address_test.py
  protostar/starknet/cheatable_cached_state.py
  protostar/starknet/cheatable_syscall_handler.py
  protostar/starknet/cheaters/block_info.py
  protostar/starknet/types.py
  protostar/starknet_gateway/account_tx_version_detector.py
  protostar/starknet_gateway/block_explorer/block_explorer.py
  protostar/starknet_gateway/block_explorer/combined_block_explorer.py
  protostar/starknet_gateway/block_explorer/fake_block_explorer.py
  protostar/starknet_gateway/block_explorer/stark_scan_block_explorer.py
  protostar/starknet_gateway/block_explorer/viewblock_block_explorer.py
  protostar/starknet_gateway/block_explorer/voyager_block_explorer.py
  protostar/starknet_gateway/contract_function_factory.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/gateway_response.py
  protostar/starknet_gateway/starknet_request.py
  protostar/starknet_gateway/starknet_request_test.py
  protostar/testing/cheatcodes/deploy_cheatcode.py
  protostar/testing/cheatcodes/expect_call_cheatcode.py
  protostar/testing/cheatcodes/mock_call_cheatcode.py
  protostar/testing/cheatcodes/prepare_cheatcode.py
  protostar/testing/cheatcodes/roll_cheatcode.py
  protostar/testing/cheatcodes/warp_cheatcode.py
  protostar/testing/starkware/test_execution_state.py
  protostar/testing/test_environment_exceptions.py
  protostar/testing/test_environment_exceptions_test.py
  tests/_conftest/devnet/devnet_account.py
  tests/_conftest/devnet/devnet_account_preparator.py
  tests/_conftest/devnet/faucet_contract.py
  tests/conftest.py
  tests/e2e/test_gateway_commands.py
  tests/e2e/test_migrating.py
  tests/integration/conftest.py
  tests/integration/deploying/declare_command_test.py
  tests/integration/gateway/gateway_facade_test.py
  tests/integration/migrator/conftest.py
  tests/integration/migrator/migrator_invoke_cheatcode_test.py
  tests/integration/protostar_fixture.py
Labels: size/L

#1180 Fix parsing non-string values from configuration file
  protostar/argument_parser/arg_type.py
  protostar/argument_parser/arg_type_test.py
  protostar/argument_parser/argument.py
  protostar/argument_parser/argument_parser_facade.py
  protostar/argument_parser/argument_parser_facade_test.py
  protostar/argument_parser/conftest.py
  protostar/argument_parser/unparser.py
  protostar/argument_parser/unparser_test.py
Labels: size/M

#1182 Adapt migrator for UDC + fix tests
  protostar/migrator/cheatcodes/migrator_deploy_contract_cheatcode.py
  protostar/migrator/migrator_test.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/starknet_request.py
  protostar/testing/cheatcodes/deploy_contract_cheatcode.py
  tests/e2e/test_gateway_commands.py
  tests/e2e/test_migrating.py
  tests/e2e/test_migrating/migration_signed_invokes.cairo
  tests/e2e/test_migrating/migration_up_down.cairo
  tests/integration/migrator/compiled_account_contract_tx_v0.py
  tests/integration/migrator/migrator_call_cheatcode_test.py
  tests/integration/migrator/migrator_deploy_contract_cheatcode_test.py
  tests/integration/migrator/migrator_invoke_cheatcode_test.py
  tests/integration/migrator/migrator_test.py
  website/docs/cli-reference.md
Labels: size/M

#1190 UDC support - Docs
  protostar/commands/deploy_command.py
  website/docs/tutorials/08-interacting-with-starknet/04-deploy.md
  website/docs/tutorials/09-migrations/declare.md
  website/docs/tutorials/09-migrations/deploy-contract.md
  website/docs/tutorials/09-migrations/network-config.md
Labels: size/S

#1188 Remove generating `cairo-paths`
  protostar/compiler/project_cairo_path_builder.py
  protostar/composition_root.py
  protostar/testing/test_runner.py
  tests/integration/project_compiler/project_compiler_test.py
  tests/integration/protostar_fixture.py
Labels: size/S

#1196 Raise error when test parameters not found
  protostar/testing/environments/fuzz_test_execution_environment.py
  tests/e2e/fixtures/test_fuzz.cairo
  tests/integration/cheatcodes/assume_and_reject/assume_and_reject_test.cairo
  tests/integration/cheatcodes/assume_and_reject/assume_and_reject_together_test.cairo
  tests/integration/fuzzing/basic_test.cairo
  tests/integration/fuzzing/fuzzing_test.py
  tests/integration/fuzzing/hypothesis_multiple_errors_test.cairo
  tests/integration/fuzzing/max_examples_in_setup_case_test.cairo
  tests/integration/fuzzing/max_examples_in_setup_hook_test.cairo
  tests/integration/fuzzing/max_examples_invalid_arguments_test.cairo
  tests/integration/fuzzing/shared_state_test.cairo
  tests/integration/fuzzing/state_isolation_test.cairo
Labels: size/S

#1205 Hotifx — Protostar throws an error if `cairo-path` doesn't exist, preventing installing packages
  protostar/commands/build_command.py
  protostar/commands/test/test_command.py
  website/docs/cli-reference.md
Labels: size/XS

#1211 Remove migrations feature & related docs
  protostar/commands/__init__.py
  protostar/commands/migrate_command.py
  protostar/commands/migrate_command_test.py
  protostar/composition_root.py
  protostar/migrator/__init__.py
  protostar/migrator/cheatcodes/__init__.py
  protostar/migrator/cheatcodes/migrator_call_cheatcode.py
  protostar/migrator/cheatcodes/migrator_declare_cheatcode.py
  protostar/migrator/cheatcodes/migrator_deploy_contract_cheatcode.py
  protostar/migrator/cheatcodes/migrator_invoke_cheatcode.py
  protostar/migrator/cheatcodes/network_config.py
  protostar/migrator/migrator.py
  protostar/migrator/migrator_cheatcodes_factory.py
  protostar/migrator/migrator_contract_identifier_resolver.py
  protostar/migrator/migrator_datetime_state.py
  protostar/migrator/migrator_datetime_state_test.py
  protostar/migrator/migrator_execution_environment.py
  protostar/migrator/migrator_test.py
  protostar/migrator/output_directory.py
  protostar/migrator/output_directory_test.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/gateway_facade_factory.py
  protostar/starknet_gateway/starknet_request.py
  protostar/starknet_gateway/starknet_request_test.py
  protostar/testing/cheatcodes/declare_cheatcode.py
  protostar/testing/cheatcodes/deploy_cheatcode.py
  protostar/testing/cheatcodes/deploy_contract_cheatcode.py
  tests/e2e/test_migrating.py
  tests/e2e/test_migrating/box_contract.cairo
  tests/e2e/test_migrating/migration_signed_invokes.cairo
  tests/e2e/test_migrating/migration_up_down.cairo
  tests/integration/commands/invoke_command_test.py
  tests/integration/conftest.py
  tests/integration/migrator/conftest.py
  tests/integration/migrator/migrator_call_cheatcode_test.py
  tests/integration/migrator/migrator_declare_cheatcode_test.py
  tests/integration/migrator/migrator_deploy_contract_cheatcode_test.py
  tests/integration/migrator/migrator_invoke_cheatcode_test.py
  tests/integration/migrator/migrator_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/07-testing/02-cheatcodes/declare.md
  website/docs/tutorials/07-testing/02-cheatcodes/deploy-contract.md
  website/docs/tutorials/09-migrations/README.md
  website/docs/tutorials/09-migrations/_category_.yaml
  website/docs/tutorials/09-migrations/call.md
  website/docs/tutorials/09-migrations/declare.md
  website/docs/tutorials/09-migrations/deploy-contract.md
  website/docs/tutorials/09-migrations/invoke.md
  website/docs/tutorials/09-migrations/network-config.md
  website/docusaurus.config.js
  website/package.json
Labels: size/XXL

#1140 Support different inputs format in CLI
  docs_generator/reference_docs_generator.py
  docs_generator/reference_docs_generator_test.py
  protostar/argument_parser/argument.py
  protostar/argument_parser/argument_parser_facade.py
  protostar/argument_parser/argument_parser_facade_test.py
  protostar/cli/common_arguments.py
  protostar/cli/protostar_arg_type.py
  protostar/commands/build_command.py
  protostar/commands/cairo_migrate_command.py
  protostar/commands/call_command.py
  protostar/commands/deploy_command.py
  protostar/commands/format_command.py
  protostar/commands/invoke_command.py
  protostar/commands/test/test_command.py
  protostar/start.py
  tests/integration/commands/call_command_test.py
  tests/integration/commands/getter_contract.cairo
  tests/integration/commands/invoke_command_test.py
  tests/integration/deploying/deploy_command_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
  website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
  website/docs/tutorials/08-interacting-with-starknet/02-call.md
Labels: size/M

#1213 Add scope to expect_call cheatcode
  protostar/starknet/cheatable_cached_state.py
  protostar/starknet/cheatable_syscall_handler.py
  protostar/testing/cheatcodes/expect_call_cheatcode.py
  tests/integration/cheatcodes/expect_call/expect_call_test.cairo
  tests/integration/cheatcodes/expect_call/expect_call_test.py
  website/docs/tutorials/07-testing/02-cheatcodes/expect-call.md
Labels: size/M

#1199 Remove redundant strategy logic
  protostar/testing/environments/fuzz_test_execution_environment.py
  protostar/testing/fuzzing/strategy_collector.py
  protostar/testing/fuzzing/strategy_collector_test.py
  tests/integration/fuzzing/fuzzing_test.py
  tests/integration/fuzzing_strategies/one_of_test.cairo
Labels: size/S

#1209 Fix loading shared args when profile is provided
  protostar/configuration_file/argument_value_resolver.py
  protostar/configuration_file/component_test.py
Labels: size/S

#1218 Remove unsigned transactions support
  protostar/cli/common_arguments.py
  protostar/cli/signable_command_util.py
  protostar/commands/declare_command.py
  protostar/commands/invoke_command.py
  protostar/starknet_gateway/gateway_facade.py
  tests/conftest.py
  tests/e2e/test_gateway_commands.py
  tests/integration/commands/call_command_test.py
  tests/integration/commands/invoke_command_test.py
  tests/integration/deploying/deploy_command_test.py
  tests/integration/gateway/gateway_facade_test.py
  tests/integration/protostar_fixture.py
  website/docs/cli-reference.md
Labels: size/XXL

#1028 Drop the warning for unstable feature in fuzzing
  website/docs/tutorials/07-testing/03-fuzzing/README.md
Labels: size/XS

#1208 Moved initializing git into `install` command
  protostar/commands/init/project_creator/adapted_project_creator.py
  protostar/commands/init/project_creator/new_project_creator.py
  protostar/commands/install/install_command.py
  protostar/commands/install/install_package_from_repo.py
  protostar/commands/install/install_package_from_repo_test.py
  protostar/commands/install/pull_package_submodules.py
  protostar/commands/remove/removal_exceptions.py
  protostar/commands/remove/remove_package.py
  protostar/protostar_cli.py
  protostar/protostar_cli_test.py
  tests/e2e/test_misc_commands.py
Labels: size/S
