Repository software-mansion/protostar, pull requests merged in 2022-07, with the labels that each got.

#464 Make all exceptions inherit from Exception instead of BaseException
  protostar/cli/cli_app.py
  protostar/starknet/cheatable_syscall_handler.py
  protostar/utils/data_transformer_facade.py
Labels: bug

#496 Add event ABI in default cheatcode implementation
  protostar/commands/test/cheatcodes/declare_cheatcode.py
  protostar/starknet/cheatcode.py
Labels: bug

#504 Simplify DataTransformerFacade
  protostar/commands/test/cheatcodes/deploy_contract_cheatcode.py
  protostar/commands/test/cheatcodes/expect_events_cheatcode.py
  protostar/commands/test/cheatcodes/mock_call_cheatcode.py
  protostar/commands/test/cheatcodes/prepare_cheatcode.py
  protostar/commands/test/environments/setup_execution_environment.py
  protostar/commands/test/environments/test_execution_environment.py
  protostar/utils/__init__.py
  protostar/utils/abi.py
  protostar/utils/abi_test.py
  protostar/utils/data_transformer.py
  protostar/utils/data_transformer_facade.py
  website/docs/tutorials/guides/testing.md
Labels: refactor

#511 Improve assert_cairo_test_cases diffing
  tests/integration/conftest.py
Labels: refactor

#507 Reorganise documentation
  website/docs/tutorials/01-introduction.md
  website/docs/tutorials/04-compiling.md
  website/docs/tutorials/05-dependencies-management.md
  website/docs/tutorials/06-deploying.md
  website/docs/tutorials/07-testing/01-deploying-contracts.md
  website/docs/tutorials/07-testing/02-cheatcodes/README.md
  website/docs/tutorials/07-testing/02-cheatcodes/_category_.yaml
  website/docs/tutorials/07-testing/02-cheatcodes/declare.md
  website/docs/tutorials/07-testing/02-cheatcodes/deploy-contract.md
  website/docs/tutorials/07-testing/02-cheatcodes/deploy.md
  website/docs/tutorials/07-testing/02-cheatcodes/expect-events.md
  website/docs/tutorials/07-testing/02-cheatcodes/expect-revert.md
  website/docs/tutorials/07-testing/02-cheatcodes/load.md
  website/docs/tutorials/07-testing/02-cheatcodes/mock-call.md
  website/docs/tutorials/07-testing/02-cheatcodes/prepare.md
  website/docs/tutorials/07-testing/02-cheatcodes/roll.md
  website/docs/tutorials/07-testing/02-cheatcodes/start-prank.md
  website/docs/tutorials/07-testing/02-cheatcodes/store.md
  website/docs/tutorials/07-testing/02-cheatcodes/warp.md
  website/docs/tutorials/07-testing/README.md
  website/docs/tutorials/07-testing/_category_.yaml
  website/docs/tutorials/guides/testing.md
  website/docusaurus.config.js
  website/package.json
  website/sidebars.js
  website/yarn.lock
Labels: documentation

#498 Properly pickle reported exceptions
  protostar/commands/test/test_cases.py
  protostar/commands/test/test_environment_exceptions.py
  protostar/commands/test/test_environment_exceptions_test.py
  protostar/commands/test/test_runner.py
Labels: refactor

#526 Isolate state between fuzz test runs
  protostar/commands/test/environments/fuzz_test_execution_environment.py
  tests/integration/fuzzing/fuzzing_test.py
  tests/integration/fuzzing/state_isolation_test.cairo
Labels: bug
