Repository software-mansion/protostar, pull requests merged in 2023-05, with the labels that each got.

#1856 1820 nicer exceptions
  protostar/cairo/cairo_bindings.py
  protostar/cairo/cairo_exceptions.py
  protostar/commands/cairo1_commands/build_cairo1_command.py
  protostar/compiler/project_compiler.py
  protostar/testing/test_collector.py
  tests/integration/cairo1/compiler_bindings/test_typecheck_test.py
Labels: size/S

#1858 Fix version in `pyproject.toml`
  poetry.lock
  pyproject.toml
Labels: size/XS

#1862 Remove unused `AccountTxVersionDetector`
  protostar/starknet_gateway/account_tx_version_detector.py
  protostar/starknet_gateway/gateway_facade.py
Labels: size/S

#1865 Fix misleading comments in the bindings installing script
  scripts/install_cairo_bindings.sh
Labels: size/XS

#1877 1799 remove codeowners
  .github/CODEOWNERS
Labels: size/S

#1875 Fix gas support
  protostar/cairo/cairo_function_runner_facade.py
  tests/e2e/cairo1/test_building_contracts_scarb.py
  tests/e2e/cairo1/test_testing_scarb.py
  tests/integration/cairo1/misc/gas_test/test.cairo
Labels: size/S

#1864 Reduce functionality of `ProjectCompiler`
  protostar/cairo/cairo_bindings.py
  protostar/cairo_testing/cairo1_test_runner.py
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cairo_testing/cairo_test_execution_state.py
  protostar/cairo_testing/execution_environments/cairo_setup_case_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_setup_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_test_execution_environment.py
  protostar/cheatable_starknet/callable_hint_locals/declare_hint_local.py
  protostar/commands/cairo1_commands/declare_cairo1_command.py
  protostar/compiler/__init__.py
  protostar/compiler/project_compiler.py
  protostar/composition_root.py
  protostar/contract_path_resolver/__init__.py
  protostar/contract_path_resolver/contract_path_resolver.py
  protostar/testing/starkware/contract_based_test_execution_state.py
  protostar/testing/starkware/test_execution_state.py
  protostar/testing/test_runner.py
  tests/integration/_conftest/protostar_fixture_factory.py
  tests/integration/commands/declare_cairo1_command_test.py
Labels: size/M

#1893 Fix events for cairo1
  protostar/cheatable_starknet/controllers/contracts.py
  tests/integration/cairo1/misc/events_test/data/minimal/cairo_project.toml
  tests/integration/cairo1/misc/events_test/data/minimal/lib.cairo
  tests/integration/cairo1/misc/events_test/events_test.cairo
  tests/integration/cairo1/misc/events_test/test_events.py
Labels: size/S

#1890 `roll` + `stop_roll`
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cheatable_starknet/callable_hint_locals/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/start_roll_hint_local.py
  protostar/cheatable_starknet/controllers/block_info.py
  tests/integration/cairo1/hint_locals/start_roll/data/proxy/cairo_project.toml
  tests/integration/cairo1/hint_locals/start_roll/data/proxy/lib.cairo
  tests/integration/cairo1/hint_locals/start_roll/data/simple/cairo_project.toml
  tests/integration/cairo1/hint_locals/start_roll/data/simple/lib.cairo
  tests/integration/cairo1/hint_locals/start_roll/data/storing_block_number/cairo_project.toml
  tests/integration/cairo1/hint_locals/start_roll/data/storing_block_number/lib.cairo
  tests/integration/cairo1/hint_locals/start_roll/data/storing_constructor_blk_number/cairo_project.toml
  tests/integration/cairo1/hint_locals/start_roll/data/storing_constructor_blk_number/lib.cairo
  tests/integration/cairo1/hint_locals/start_roll/start_roll_test.cairo
  tests/integration/cairo1/hint_locals/start_roll/test_start_roll.py
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/start_roll.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/stop_prank.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/stop_roll.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/stop_warp.md
Labels: size/M

#1891 Add design document for mocking tx info
  design_docs/mock-tx-info.md
Labels: size/M

#1901 Add tests with args for events in cairo1
  tests/integration/cairo1/misc/events_test/data/simple/cairo_project.toml
  tests/integration/cairo1/misc/events_test/data/simple/lib.cairo
  tests/integration/cairo1/misc/events_test/data/with_data/cairo_project.toml
  tests/integration/cairo1/misc/events_test/data/with_data/lib.cairo
  tests/integration/cairo1/misc/events_test/events_test.cairo
  tests/integration/cairo1/misc/events_test/test_events.py
Labels: size/S

#1917 Updated readme
  README.md
Labels: size/S

#1927 Fix missing cache for protostar rust bindings
  .circleci/config.yml
Labels: size/XS

#1931 [CI] Notify only about (pre)releases candidates from master
  .circleci/config.yml
Labels: size/XS

#1920 Remove redundant info about `RevertedTransaction` from docs
  website/docs/cairo-1/05-testing/cheatcodes-reference/README.md
  website/docs/cairo-1/05-testing/cheatcodes-reference/call.md
  website/docs/cairo-1/05-testing/cheatcodes-reference/deploy.md
  website/docs/cairo-1/05-testing/cheatcodes-reference/invoke.md
Labels: size/S

#1930 Check multicall section validity for cairo1
  website/docs/cairo-1/06-interacting-with-starknet/06-multicall.md
Labels: size/XS

#1925 Document `RevertedTransaction` for integration tests
  website/docs/cairo-1/05-testing/02-integration-testing.md
Labels: size/S

#1933 Fix snapshot arguments in docs
  website/docs/cairo-1/05-testing/02-integration-testing.md
  website/docs/cairo-1/05-testing/03-cheatcodes.md
  website/docs/cairo-1/05-testing/README.md
  website/docs/cairo-1/05-testing/cheatcodes-reference/call.md
  website/docs/cairo-1/05-testing/cheatcodes-reference/start_roll.md
Labels: size/S

#1936 [CI] Patch github checks to report success on approvals
  .circleci/config.yml
  scripts/circle_patch_approvals.sh
Labels: size/M

#1797 Output `class_hash` and `compiled_class_hash` when build cairo1
  protostar/cairo/bindings/cairo_bindings.py
  protostar/cairo/contract_class.py
  protostar/cheatable_starknet/callable_hint_locals/declare_hint_local.py
  protostar/commands/cairo1_commands/build_command.py
  protostar/commands/cairo1_commands/declare_cairo1_command.py
  protostar/compiler/cairo1_contract_compiler.py
  protostar/composition_root.py
  tests/e2e/cairo1/test_cairo1_building.py
  tests/e2e/cairo_0_1_mixed/test_cairo_0_1_mixed_building.py
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/_conftest/protostar_fixture_factory.py
  tests/integration/cairo1/build_cairo1_test.py
  tests/integration/cairo1/compiler_bindings/starknet_contracts_compiler_test.py
  website/docs/cairo-1/06-interacting-with-starknet/09-compiling.md
  website/docs/cli-reference.md
Labels: size/L

#1953 [CI] Further cost optimization
  .circleci/config.yml
Labels: size/M

#1961 Updated dev readme
  scripts/install_cairo_bindings.sh
Labels: size/XS

#1960 Fix print fail
  protostar/cheatable_starknet/controllers/io.py
  tests/integration/cairo1/compiler_bindings/test_print.py
  tests/integration/cairo1/compiler_bindings/test_print/print_test.cairo
Labels: size/S

#1976 Rename contracts to contract in template
  templates/cairo1/src/contract.cairo
  templates/cairo1/src/contract/hello_starknet.cairo
  templates/cairo1/src/lib.cairo
  website/.gitignore
  website/docs/cairo-1/03-project-initialization.md
  website/docs/cairo-1/05-testing/02-integration-testing.md
  website/docs/cairo-1/06-interacting-with-starknet/08-scripting.md
Labels: size/S

#1977 Remove lib-path from cairo 1
  protostar/commands/legacy_commands/init_cairo0/project_creator/new_project_creator.py
  templates/cairo1/protostar.toml
  templates/cairo1_minimal/protostar.toml
  tests/e2e/conftest.py
  website/docs/cairo-1/04-protostar-toml.md
Labels: size/S

#1902 Bump cairo lang to 0.11.1.1 and starknet-devnet to 0.5.2
  poetry.lock
  protostar/cairo_testing/cairo_test_execution_state.py
  protostar/cheatable_starknet/cheatables/cheatable_cached_state.py
  protostar/cheatable_starknet/cheatables/cheatable_deprecated_syscall_handler.py
  protostar/commands/legacy_commands/test_cairo0/test_cairo0_command.py
  protostar/profiler/__init__.py
  protostar/profiler/contract_profiler.py
  protostar/profiler/contract_profiler_test.py
  protostar/profiler/pprof.py
  protostar/profiler/transaction_profiler.py
  protostar/profiler/transaction_profiler_test.py
  protostar/starknet/cheatable_cached_state.py
  protostar/starknet/cheatable_execute_entry_point.py
  protostar/starknet/cheatable_state.py
  protostar/starknet/cheatable_syscall_handler.py
  protostar/starknet/cheatcode.py
  protostar/starknet/forkable_starknet.py
  protostar/testing/environments/contract_based_test_execution_environment.py
  protostar/testing/starkware/contract_based_test_execution_state.py
  pyproject.toml
  tests/e2e/test_testing.py
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/cheatcodes/prepare/prepare_test.cairo
  tests/integration/conftest.py
  tests/integration/profile_tests/basic_contract.cairo
  tests/integration/profile_tests/dummy_test.cairo
  tests/integration/profile_tests/example_profile_contract_test.cairo
  tests/integration/profile_tests/profile_test.py
  website/docs/cli-reference.md
  website/docs/legacy/12-profiling.md
Labels: size/XXL

#2010 Remove unnecessary repetition
  website/docs/cairo-1/06-interacting-with-starknet/02-declare.md
Labels: size/XS

#2018 Hotfix docs build
  protostar/configuration_file/configuration_file.py
  website/docusaurus.config.js
Labels: size/XS

#2012 Disable output buffering for tests + build docs on all PRs
  .circleci/config.yml
Labels: size/S

#2013 version bump
  pyproject.toml
Labels: size/XS

#2025 [CI] Do not parallelize tests on mac runners
  .circleci/config.yml
Labels: size/S
