Repository software-mansion/protostar, pull requests merged in 2023-03, with the labels that each got.

#1546 Flatten code in compiler
  protostar/starknet/starknet_compiler.py
Labels: size/S

#1522 Support for cairo1 tests
  .github/workflows/build_binaries.yml
  .github/workflows/builds_on_mac.yml
  .github/workflows/checks.yml
  protostar/cairo/cairo1_test_suite_parser.py
  protostar/cairo/cairo_bindings.py
  protostar/cairo/cairo_function_executor.py
  protostar/cairo/cairo_function_runner_facade.py
  protostar/cairo_testing/cairo1_test_collector.py
  protostar/cairo_testing/cairo1_test_runner_adapter.py
  protostar/cairo_testing/cairo_injectable_function_runner.py
  protostar/cairo_testing/cairo_test_runner.py
  protostar/cairo_testing/execution_environments/cairo_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_setup_case_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_setup_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_test_execution_environment.py
  protostar/commands/test/test_command.py
  protostar/self/protostar_directory.py
  protostar/self/protostar_directory_test.py
  protostar/testing/environments/contract_based_test_execution_environment.py
  protostar/testing/environments/fuzz_test_execution_environment.py
  protostar/testing/environments/setup_case_execution_environment.py
  protostar/testing/environments/setup_execution_environment.py
  protostar/testing/test_case_runners/cairo1_test_case_runner.py
  protostar/testing/test_suite.py
  protostar_cairo/protostar/lib.cairo
  scripts/install_cairo_bindings.sh
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/_conftest/protostar_fixture_factory.py
  tests/integration/cairo1_compiler_bindings/library_functions_test.py
  tests/integration/cairo1_compiler_bindings/tests_collector_and_compiler_test.py
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test.py
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/broken/test_cairo1_broken_suite.cairo
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/external_lib_foo/cairo_project.toml
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/external_lib_foo/foo.cairo
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/external_lib_foo/lib.cairo
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/multiple_suites/test_cairo1.cairo
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/multiple_suites/test_cairo1_two_cases.cairo
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/test_cairo1.cairo
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/test_cairo1_empty_suite.cairo
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/test_cairo1_ext_lib.cairo
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/test_cairo1_two_cases.cairo
  tests/integration/pure_cairo_vm/cairo1_integration/data/cairo_project.toml
  tests/integration/pure_cairo_vm/cairo1_integration/data/lib.cairo
Labels: size/XL

#1527 Add cairo1 invoke test
  protostar/cairo/cairo_function_runner_facade.py
  tests/integration/cairo1_compiler_bindings/library_functions_test.py
  tests/integration/cairo1_compiler_bindings/library_functions_test/invoke_test.cairo
Labels: size/M

#1549 `init` command for cairo 1
  protostar/cairo/__init__.py
  protostar/cairo/cairo_enum.py
  protostar/cairo/cairo_enum_test.py
  protostar/commands/init/init_command.py
  protostar/commands/init/project_creator/_project_creator.py
  protostar/commands/init/project_creator/new_project_creator.py
  protostar/composition_root.py
  templates/cairo0/protostar.toml
  templates/cairo0/src/main.cairo
  templates/cairo0/tests/test_main.cairo
  templates/cairo1/protostar.toml
  templates/cairo1/src/main_cairo1.cairo
  templates/cairo1/tests/test_main_cairo1.cairo
  tests/integration/_conftest/protostar_fixture_factory.py
  website/docs/cli-reference.md
Labels: size/M

#1548 Cairo1 tests e2e
  protostar.spec
  protostar/commands/cairo1_commands/__init__.py
  protostar/commands/cairo1_commands/test_cairo1_command.py
  protostar/commands/test/__init__.py
  protostar/commands/test/test_command.py
  protostar/compiler/__init__.py
  protostar/compiler/project_cairo_path_builder.py
  protostar/compiler/project_compiler.py
  protostar/composition_root.py
  protostar/protostar_cli.py
  protostar_cairo/cairo_project.toml
  tests/e2e/cairo1/test_cairo1_testing.py
  tests/e2e/conftest.py
  tests/e2e/fixtures/cairo1_project/libraries/external_lib_bar/bar.cairo
  tests/e2e/fixtures/cairo1_project/libraries/external_lib_bar/cairo_project.toml
  tests/e2e/fixtures/cairo1_project/libraries/external_lib_bar/lib.cairo
  tests/e2e/fixtures/cairo1_project/libraries/external_lib_foo/cairo_project.toml
  tests/e2e/fixtures/cairo1_project/libraries/external_lib_foo/foo.cairo
  tests/e2e/fixtures/cairo1_project/libraries/external_lib_foo/lib.cairo
  tests/e2e/fixtures/cairo1_project/protostar.toml
  tests/e2e/fixtures/cairo1_project/tests/test_a.cairo
  tests/e2e/fixtures/cairo1_project/tests/test_with_deps.cairo
  website/docs/cli-reference.md
Labels: size/M

#1551 Cairo1 build command
  protostar/__init__.py
  protostar/cairo/cairo_bindings.py
  protostar/commands/__init__.py
  protostar/commands/cairo1_commands/cairo1_build_command.py
  protostar/compiler/project_compiler.py
  protostar/composition_root.py
  templates/cairo1/src/main.cairo
  templates/cairo1/tests/test_main.cairo
  tests/e2e/cairo1/__init__.py
  tests/e2e/cairo1/test_building.py
  tests/e2e/conftest.py
  tests/e2e/fixtures/basic_cairo1.cairo
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/_conftest/protostar_fixture_factory.py
  tests/integration/cairo1_compiler_bindings/starknet_contracts_compiler_test.py
  website/docs/cli-reference.md
Labels: size/M

#1553 Convert bindings errors
  protostar/cairo/cairo_bindings.py
  protostar/cairo/cairo_exceptions.py
  protostar/testing/test_collector.py
  tests/integration/cairo1_compiler_bindings/test_typecheck_test.py
Labels: size/S

#1586 Cairo1 testing docs
  website/docs/tutorials/01-introduction.md
  website/docs/tutorials/07-testing/04-e2e.md
  website/docs/tutorials/07-testing/README.md
  website/docs/tutorials/08-cairo-1-support/01-testing.md
  website/docs/tutorials/08-cairo-1-support/_category_.yaml
  website/docs/tutorials/09-interacting-with-starknet/01-invoke.md
  website/docs/tutorials/09-interacting-with-starknet/02-call.md
  website/docs/tutorials/09-interacting-with-starknet/03-declare.md
  website/docs/tutorials/09-interacting-with-starknet/04-deploy.md
  website/docs/tutorials/09-interacting-with-starknet/05-deploy-account.md
  website/docs/tutorials/09-interacting-with-starknet/06-signing.md
  website/docs/tutorials/09-interacting-with-starknet/07-multicall.md
  website/docs/tutorials/09-interacting-with-starknet/README.md
  website/docs/tutorials/09-interacting-with-starknet/_category_.yaml
  website/docs/tutorials/09-interacting-with-starknet/scripting.md
  website/docs/tutorials/10-migrations/README.md
  website/docs/tutorials/10-migrations/_category_.yaml
  website/docs/tutorials/11-formatting.md
  website/docs/tutorials/12-profiling.md
Labels: size/M

#1572 Handle cairo1 failed tests
  protostar/cairo/cairo_function_runner_facade.py
  protostar/cairo_testing/cairo_injectable_function_runner.py
  tests/e2e/cairo1/test_cairo1_testing.py
  tests/e2e/fixtures/cairo1/failing_test.cairo
  tests/integration/cairo1/cairo_runner_facade_test.py
  tests/integration/cairo1/cairo_runner_facade_test/test.cairo
  tests/integration/cairo1_compiler_bindings/library_functions_test.py
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test.py
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test/test_cairo1_failing.cairo
Labels: size/M

#1575 `test-cairo1` comprehensive e2e tests
  tests/e2e/cairo1/test_cairo1_testing.py
  tests/e2e/fixtures/cairo1/nested/test_nested.cairo
  tests/e2e/fixtures/cairo1/test_a.cairo
  tests/e2e/fixtures/cairo1/test_with_deps.cairo
  tests/e2e/fixtures/cairo1_project/tests/.keep
Labels: size/M

#1588 `init-cairo1` docs
  website/docs/tutorials/08-cairo-1-support/01-project-initialization.md
  website/docs/tutorials/08-cairo-1-support/02-testing.md
Labels: size/S

#1592 Remove --existing flag from `init-cairo1`
  protostar/__init__.py
  protostar/commands/__init__.py
  protostar/commands/cairo1_commands/__init__.py
  protostar/commands/cairo1_commands/build_cairo1_command.py
  protostar/commands/cairo1_commands/init_cairo1_command.py
  protostar/commands/init/init_command.py
  protostar/commands/init/project_creator/adapted_project_creator.py
  protostar/composition_root.py
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/_conftest/protostar_fixture_factory.py
  tests/integration/conftest.py
  website/docs/cli-reference.md
Labels: size/M

#1603 Add docs about cairo 1 modules
  website/docs/tutorials/08-cairo-1-support/01-project-initialization.md
Labels: size/S

#1613 Release fix: corelib detection in tests
  protostar/commands/test/test_command.py
Labels: size/XS

#1609 Test for cairo1 modules
  tests/e2e/cairo1/test_cairo1_testing.py
  tests/e2e/fixtures/cairo_0_1_mixed/protostar.toml
  tests/e2e/fixtures/cairo_0_1_mixed/src/cairo_project.toml
  tests/e2e/fixtures/cairo_0_1_mixed/src/lib.cairo
  tests/e2e/fixtures/cairo_0_1_mixed/src/main.cairo
  tests/e2e/fixtures/cairo_0_1_mixed/src/mod1_cairo1.cairo
  tests/e2e/fixtures/cairo_0_1_mixed/src/mod1_cairo1/mod1_code.cairo
  tests/e2e/fixtures/cairo_0_1_mixed/src/mod2_cairo1.cairo
  tests/e2e/fixtures/cairo_0_1_mixed/src/mod2_cairo1/mod2_code.cairo
  tests/e2e/fixtures/cairo_0_1_mixed/tests/test_main.cairo
Labels: size/S

#1619 Set rust version to `nightly-2022-11-03` in `install_cairo_bindings.sh`
  scripts/install_cairo_bindings.sh
Labels: size/XS

#1583 Fix the example cheatcode
  protostar/testing/environments/fuzz_test_execution_environment.py
  tests/integration/fuzzing/fuzzing_test.py
  tests/integration/fuzzing/parameterized_test.cairo
Labels: size/S

#1623 Modular protostar - architecture
  design_docs/img/diagram.png
  design_docs/protostar-architecture.md
Labels: size/S

#1602 Separate test commands
  protostar/commands/cairo1_commands/test_cairo1_command.py
Labels: size/M

#1624 Add prepare cairo1 test
  tests/integration/cairo1_compiler_bindings/library_functions_test.py
  tests/integration/cairo1_compiler_bindings/library_functions_test/prepare_test.cairo
Labels: size/S

#1639 Add `merge_group` event trigger for essential checks
  .github/workflows/build_docs.yml
  .github/workflows/builds_on_mac.yml
  .github/workflows/checks.yml
Labels: size/XS

#1651 Update branding
  README.md
  readme/protostar-logo--dark.svg
  readme/protostar-logo--light.svg
  website/docusaurus.config.js
  website/package.json
  website/src/components/HomepageFeature/HomepageFeature.tsx
  website/src/components/HomepageFeature/styles.module.css
  website/src/components/HomepageHeader/HomepageHeader.tsx
  website/src/components/HomepageHeader/styles.module.css
  website/src/components/StarIcon/StarIcon.tsx
  website/src/components/StarIcon/index.ts
  website/src/components/Stars/Stars.tsx
  website/src/components/index.ts
  website/src/css/custom.css
  website/src/pages/index.tsx
  website/src/theme/DocPage/Layout/Main/index.js
  website/static/apple-touch-icon.png
  website/static/favicon.ico
  website/static/favicon.svg
  website/static/icon-192.png
  website/static/icon-512.png
  website/static/img/favicon.ico
  website/static/img/protostar-logo--dark.png
  website/static/img/protostar-logo--light.png
  website/static/img/protostar-title--dark.svg
  website/static/img/protostar-title--light.svg
  website/static/img/protostar-wide--dark.svg
  website/static/img/protostar-wide--light.svg
  website/static/img/star--dark.png
  website/static/img/star--light.png
  website/static/manifest.json
  website/static/og-image.png
  website/yarn.lock
Labels: size/XXL

#1669 Change scope of errors reraised in bindings
  protostar/cairo/cairo_bindings.py
Labels: size/XS

#1688 `tmp_path` fixtures wrappers
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/deploying/declare_command_test.py
  tests/integration/deploying/deploy_command_test.py
  tests/integration/gateway/uint256_as_input_test.py
Labels: size/S

#1625 Declare cheatcode
  .pylintrc
  protostar/cairo_testing/cairo1_test_runner.py
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cairo_testing/cairo_test_execution_state.py
  protostar/cairo_testing/execution_environments/cairo_setup_case_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_setup_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_test_execution_environment.py
  protostar/cheatable_starknet/callable_hint_locals/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/declare_cairo0_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/declare_hint_local.py
  protostar/cheatable_starknet/controllers/contracts.py
  protostar/commands/build_command.py
  protostar/compiler/__init__.py
  protostar/compiler/cairo0_project_compiler.py
  protostar/compiler/project_compiler.py
  protostar/compiler/project_compiler_exceptions.py
  protostar/compiler/project_compiler_types.py
  protostar/composition_root.py
  protostar/configuration_file/configuration_file.py
  protostar/testing/cheatcodes/declare_cheatcode.py
  protostar/testing/environments/common_test_cheatcode_factory.py
  protostar/testing/starkware/contract_based_test_execution_state.py
  protostar/testing/starkware/test_execution_state.py
  protostar/testing/test_runner.py
  tests/integration/_conftest/protostar_fixture_factory.py
  tests/integration/cairo1_hint_locals/declare/data/broken.cairo
  tests/integration/cairo1_hint_locals/declare/data/cairo0.cairo
  tests/integration/cairo1_hint_locals/declare/data/minimal.cairo
  tests/integration/cairo1_hint_locals/declare/declare_test.cairo
  tests/integration/cairo1_hint_locals/declare/test_declare.py
  tests/integration/project_compiler/project_compiler_test.py
Labels: size/XL
