Repository software-mansion/protostar, pull requests merged in 2023-07, with the labels that each got.

#2171 Correct comment
  protostar-rust/src/cheatcodes_hint_processor.rs
Labels: size/XS

#2160 [CLI] Invoke tests
  cast/.gitignore
  cast/src/main.rs
  cast/src/starknet_commands/declare.rs
  cast/src/starknet_commands/deploy.rs
  cast/src/starknet_commands/invoke.rs
  cast/tests/data/contracts/balance/Scarb.toml
  cast/tests/data/contracts/balance/src/lib.cairo
  cast/tests/e2e/helpers/constants.rs
  cast/tests/e2e/helpers/devnet.rs
  cast/tests/e2e/helpers/fixtures.rs
  cast/tests/e2e/helpers/mod.rs
  cast/tests/e2e/invoke.rs
  cast/tests/e2e/main.rs
  cast/tests/utils/build_contracts.sh
  cast/tests/utils/prepare_for_tests.sh
Labels: size/M

#2165 [CLI] Test call
  cast/tests/data/contracts/map/Scarb.toml
  cast/tests/data/contracts/map/src/lib.cairo
  cast/tests/e2e/call.rs
  cast/tests/e2e/helpers/constants.rs
  cast/tests/e2e/helpers/fixtures.rs
  cast/tests/e2e/invoke.rs
  cast/tests/e2e/main.rs
Labels: size/M

#2179 [CLI] format code
  cast/src/lib.rs
  cast/src/main.rs
  cast/src/starknet_commands/call.rs
  cast/src/starknet_commands/declare.rs
  cast/src/starknet_commands/invoke.rs
  cast/tests/e2e/helpers/fixtures.rs
Labels: size/M

#2177 Bump version to 0.14.0
  poetry.lock
  pyproject.toml
Labels: size/XS

#2181 [CLI] Check transaction receipt in tests
  cast/Cargo.lock
  cast/Cargo.toml
  cast/tests/e2e/helpers/fixtures.rs
  cast/tests/e2e/invoke.rs
Labels: size/M

#2195 Delete dependabot config
  .github/dependabot.yml
Labels: size/S

#2196 Legacy annoucements
  README.md
  website/docusaurus.config.js
Labels: size/L
