Repository software-mansion/protostar, pull requests merged in 2023-02, with the labels that each got.

#1429 `stop_warp` & `stop_roll` cheatcodes
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cheatable_starknet/callable_hint_locals/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/roll_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/stop_roll_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/stop_warp_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/warp_hint_local.py
  protostar/cheatable_starknet/controllers/block_info.py
  tests/integration/pure_cairo_vm/cheatcodes/stop_roll/stop_roll_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/stop_roll/stop_roll_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/stop_warp/stop_warp_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/stop_warp/stop_warp_test.cairo
Labels: size/M

#1412 Cairo Cheatcode — Expect events
  protostar/cairo_testing/__init__.py
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cairo_testing/cairo_test_execution_state.py
  protostar/cairo_testing/execution_environments/cairo_setup_case_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_setup_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_test_execution_environment.py
  protostar/cheatable_starknet/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/expect_events_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatables/cheatable_cached_state.py
  protostar/cheatable_starknet/cheatables/cheatable_execute_entry_point.py
  protostar/cheatable_starknet/controllers/contracts.py
  protostar/cheatable_starknet/controllers/expect_events_controller.py
  protostar/cheatable_starknet/controllers/expect_events_controller_test.py
  protostar/starknet/selector.py
  protostar/starknet/selector_test.py
  protostar/testing/__init__.py
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/pure_cairo_vm/cheatcodes/expect_events/expect_event_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/expect_events/expect_events_test.cairo
  tests/integration/pure_cairo_vm/contracts/emitter.cairo
Labels: size/XL

#1441 Stop using shared `Controllers` for hint locals
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cheatable_starknet/callable_hint_locals/call_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/callable_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/declare_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/deploy_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/expect_events_cairo_cheatcode.py
  protostar/cheatable_starknet/callable_hint_locals/invoke_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/load_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/prank_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/prepare_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/roll_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/stop_roll_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/stop_warp_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/store_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/warp_hint_local.py
  protostar/cheatable_starknet/controllers/__init__.py
Labels: size/M

#1384 Add `send_message_to_l2` Cairo Cheatcode
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cheatable_starknet/callable_hint_locals/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/call_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/invoke_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/send_message_to_l2_hint_local.py
  protostar/cheatable_starknet/cheatables/cheatable_execute_entry_point.py
  protostar/cheatable_starknet/controllers/contracts.py
  tests/integration/pure_cairo_vm/cheatcodes/send_message_to_l2/send_message_to_l2_hint_local_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/send_message_to_l2/send_message_to_l2_hint_local_test.py
  tests/integration/pure_cairo_vm/contracts/l1_handler_contract.cairo
Labels: size/M

#1428 Move `contract_types` out of the root level
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cheatable_starknet/callable_hint_locals/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/declare_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/deploy_contract_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/deploy_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/expect_events_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/prepare_hint_local.py
  protostar/cheatable_starknet/controllers/contracts.py
  protostar/contract_types.py
  protostar/testing/cheatcodes/declare_cheatcode.py
  protostar/testing/cheatcodes/deploy_cheatcode.py
  protostar/testing/cheatcodes/deploy_contract_cheatcode.py
  protostar/testing/cheatcodes/prepare_cheatcode.py
Labels: size/M

#1455 Remove duplications in Git module
  protostar/commands/install/install_package_from_repo.py
  protostar/commands/install/install_package_from_repo_test.py
  protostar/commands/install/pull_package_submodules.py
  protostar/commands/install/pull_package_submodules_test.py
  protostar/commands/remove/remove_package.py
  protostar/commands/remove/remove_package_test.py
  protostar/commands/update/update_package.py
  protostar/commands/update/update_package_test.py
  protostar/git/__init__.py
  protostar/git/git.py
  protostar/git/git_helpers.py
  protostar/git/git_repository.py
  protostar/git/git_repository_test.py
  protostar/package_manager/package_info.py
  protostar/package_manager/package_info_test.py
  protostar/self/protostar_directory.py
  tests/e2e/test_package_management.py
Labels: size/L

#1460 Add `mock call` hint local
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cheatable_starknet/callable_hint_locals/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/callable_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/mock_call_hint_local.py
  protostar/cheatable_starknet/cheatables/cheatable_cached_state.py
  protostar/cheatable_starknet/cheatables/cheatable_syscall_handler.py
  protostar/cheatable_starknet/controllers/contracts.py
  protostar/starknet/selector.py
  tests/integration/pure_cairo_vm/cheatcodes/mock_call/mock_call_hint_local_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/mock_call/mock_call_hint_local_test.py
  tests/integration/pure_cairo_vm/contracts/number_provider_contract.cairo
  tests/integration/pure_cairo_vm/contracts/number_provider_proxy.cairo
Labels: size/M

#1316 Cairo bindings
  .github/workflows/builds_on_mac.yml
  .github/workflows/checks.yml
  README.md
  poetry.lock
  protostar/cairo/cairo_bindings.py
  pyproject.toml
  scripts/install_cairo_bindings.sh
  tests/integration/cairo1/parser_test.py
  tests/integration/cairo1/parser_test/compiled_test_suite.json
  tests/integration/cairo_compiler/contracts/basic_starknet_contract.cairo
  tests/integration/cairo_compiler/contracts/basic_starknet_test.cairo
  tests/integration/cairo_compiler/contracts/enum_contract.cairo
  tests/integration/cairo_compiler/contracts/roll_test.cairo
  tests/integration/cairo_compiler/prepare_files_fixture.py
  tests/integration/cairo_compiler/simple_contracts_compiler_test.py
  tests/integration/cairo_compiler/starknet_contracts_compiler_test.py
  tests/integration/cairo_compiler/tests_handling_test.py
Labels: size/L

#1473 Make git error message more descriptive
  protostar/commands/install/install_package_from_repo.py
  protostar/commands/install/install_package_from_repo_test.py
  protostar/git/git_helpers.py
  protostar/git/git_helpers_test.py
  protostar/git/git_repository.py
  protostar/git/git_repository_test.py
Labels: size/S

#1480 Store contract's ABI in deploy syscalls
  protostar/cheatable_starknet/cheatables/cheatable_syscall_handler.py
  tests/integration/pure_cairo_vm/cheatcodes/load/load_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/load/load_test.cairo
  tests/integration/pure_cairo_vm/contracts/deployer.cairo
Labels: size/S

#1488 Remove callback returned by `prank`
  protostar/cheatable_starknet/callable_hint_locals/prank_hint_local.py
Labels: size/XS

#1489 Add missing backticks in readme
  README.md
Labels: size/XS

#1433 Cairo path
  poetry.lock
  protostar/cairo/cairo_bindings.py
  scripts/install_cairo_bindings.sh
  tests/integration/cairo_compiler/tests_handling_test.py
  tests/integration/cairo_path/cairo_path_test.py
  tests/integration/cairo_path/contracts/external_lib_bar/bar.cairo
  tests/integration/cairo_path/contracts/external_lib_bar/cairo_project.toml
  tests/integration/cairo_path/contracts/external_lib_bar/lib.cairo
  tests/integration/cairo_path/contracts/external_lib_foo/cairo_project.toml
  tests/integration/cairo_path/contracts/external_lib_foo/foo.cairo
  tests/integration/cairo_path/contracts/external_lib_foo/lib.cairo
  tests/integration/cairo_path/contracts/regular_project/sample_cairo_code.cairo
  tests/integration/cairo_path/contracts/starknet_project/basic_starknet_contract.cairo
  tests/integration/cairo_path/contracts/starknet_project/basic_starknet_contract_nested_deps.cairo
  tests/integration/cairo_path/contracts/starknet_project/cairo_project.toml
  tests/integration/cairo_path/contracts/starknet_project/lib.cairo
  tests/integration/cairo_path/contracts/starknet_project/test.cairo
Labels: size/M

#1453 Remove address parameter from deploy-account command
  protostar/cli/__init__.py
  protostar/cli/common_arguments.py
  protostar/cli/signable_command_util.py
  protostar/cli/signable_command_util_test.py
  protostar/commands/declare_command.py
  protostar/commands/deploy_account_command.py
  protostar/commands/deploy_command.py
  protostar/commands/invoke/invoke_command.py
  protostar/commands/multicall_command.py
  protostar/starknet/address.py
  tests/_conftest/devnet/devnet_account_preparator.py
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/commands/deploy_account_command_test.py
  website/docs/cli-reference.md
Labels: size/M

#1503 Update bindings
  protostar/cairo/cairo_bindings.py
  tests/integration/cairo_compiler/simple_contracts_compiler_test.py
  tests/integration/cairo_compiler/tests_handling_test.py
  tests/integration/cairo_path/cairo_path_test.py
Labels: size/M

#1502 Made class_hash argument required in deploy command
  protostar/commands/deploy_command.py
  website/docs/cli-reference.md
Labels: size/XS

#1481 Add expect call hint local
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cheatable_starknet/callable_hint_locals/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/call_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/expect_call_hint_local.py
  protostar/cheatable_starknet/cheatables/cheatable_cached_state.py
  protostar/cheatable_starknet/cheatables/cheatable_syscall_handler.py
  protostar/cheatable_starknet/controllers/__init__.py
  protostar/cheatable_starknet/controllers/contracts.py
  protostar/cheatable_starknet/controllers/expect_call_controller.py
  protostar/testing/test_environment_exceptions.py
  tests/integration/pure_cairo_vm/cheatcodes/expect_call/expect_call_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/expect_call/expect_call_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/expect_call/expect_call_with_proxy_test.cairo
  tests/integration/pure_cairo_vm/contracts/basic_with_multiple_args.cairo
Labels: size/M

#1506 Simplify cairo1 compiler bindings tests
  tests/integration/cairo1_compiler_bindings/data/external_lib_bar/bar.cairo
  tests/integration/cairo1_compiler_bindings/data/external_lib_bar/cairo_project.toml
  tests/integration/cairo1_compiler_bindings/data/external_lib_bar/lib.cairo
  tests/integration/cairo1_compiler_bindings/data/external_lib_foo/cairo_project.toml
  tests/integration/cairo1_compiler_bindings/data/external_lib_foo/foo.cairo
  tests/integration/cairo1_compiler_bindings/data/external_lib_foo/lib.cairo
  tests/integration/cairo1_compiler_bindings/parser_test.py
  tests/integration/cairo1_compiler_bindings/parser_test/compiled_test_suite.json
  tests/integration/cairo1_compiler_bindings/starknet_contracts_compiler_test.py
  tests/integration/cairo1_compiler_bindings/starknet_contracts_compiler_test/basic_starknet_contract.cairo
  tests/integration/cairo1_compiler_bindings/starknet_contracts_compiler_test/basic_starknet_test.cairo
  tests/integration/cairo1_compiler_bindings/starknet_contracts_compiler_test/starknet_project/basic_starknet_contract.cairo
  tests/integration/cairo1_compiler_bindings/starknet_contracts_compiler_test/starknet_project/basic_starknet_contract_nested_deps.cairo
  tests/integration/cairo1_compiler_bindings/starknet_contracts_compiler_test/starknet_project/cairo_project.toml
  tests/integration/cairo1_compiler_bindings/starknet_contracts_compiler_test/starknet_project/lib.cairo
  tests/integration/cairo1_compiler_bindings/tests_collector_and_compiler_test.py
  tests/integration/cairo1_compiler_bindings/tests_collector_and_compiler_test/enum_contract.cairo
  tests/integration/cairo1_compiler_bindings/tests_collector_and_compiler_test/roll_test.cairo
  tests/integration/cairo1_compiler_bindings/tests_collector_and_compiler_test/test_with_deps.cairo
  tests/integration/cairo_compiler/prepare_files_fixture.py
  tests/integration/cairo_compiler/starknet_contracts_compiler_test.py
  tests/integration/cairo_compiler/tests_handling_test.py
  tests/integration/cairo_path/cairo_path_test.py
  tests/integration/cairo_path/contracts/regular_project/sample_cairo_code.cairo
Labels: size/L

#1517 Update CODEOWNERS
  .github/CODEOWNERS
Labels: size/S

#1516 Catch wrong value of private key
  README.md
  protostar/cli/common_arguments.py
  protostar/cli/signable_command_util.py
  protostar/cli/signable_command_util_test.py
  protostar/commands/call/call_command.py
  protostar/commands/declare_command.py
  protostar/commands/deploy_command.py
  protostar/commands/invoke/invoke_command.py
  website/docs/cli-reference.md
  website/docs/tutorials/08-interacting-with-starknet/01-invoke.md
  website/docs/tutorials/08-interacting-with-starknet/06-signing.md
Labels: size/M

#1528 Added Cairo1 `warp` test
  tests/integration/cairo1_compiler_bindings/library_functions_test.py
  tests/integration/cairo1_compiler_bindings/library_functions_test/warp_test.cairo
Labels: size/S

#1547 Set fixed poetry version to 1.3.2 in all Actions
  .github/workflows/build_binaries.yml
  .github/workflows/builds_on_mac.yml
  .github/workflows/checks.yml
Labels: size/S

#1532 Added depth 2 tests for warp and roll
  tests/integration/pure_cairo_vm/cheatcodes/roll/roll_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/roll/roll_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/send_message_to_l2/send_message_to_l2_hint_local_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/send_message_to_l2/send_message_to_l2_hint_local_test.py
  tests/integration/pure_cairo_vm/cheatcodes/stop_roll/stop_roll_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/stop_roll/stop_roll_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/stop_warp/stop_warp_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/stop_warp/stop_warp_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/warp/warp_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/warp/warp_test.cairo
  tests/integration/pure_cairo_vm/contracts/l1_handler_contract.cairo
  tests/integration/pure_cairo_vm/contracts/roll_contract.cairo
  tests/integration/pure_cairo_vm/contracts/roll_warp_tester.cairo
  tests/integration/pure_cairo_vm/contracts/warp_contract.cairo
Labels: size/M

#1538 Display more informative error message when account is not deployed (declare command)
  protostar/starknet_gateway/gateway_facade.py
Labels: size/S
