Repository software-mansion/protostar, pull requests merged in 2023-01, with the labels that each got.

#1317 Added testnet2 config
  protostar/cli/network_command_util_test.py
  protostar/starknet_gateway/block_explorer/stark_scan_block_explorer.py
  protostar/starknet_gateway/block_explorer/viewblock_block_explorer.py
  protostar/starknet_gateway/block_explorer/voyager_block_explorer.py
  protostar/starknet_gateway/network_config.py
  website/docs/cli-reference.md
Labels: size/S

#1300 Add warp, roll, and contract deployment cheats for cairo test runner
  protostar/contract_types.py
  protostar/starknet/__init__.py
  protostar/starknet/cheatable_cached_state.py
  protostar/starknet/cheaters/__init__.py
  protostar/starknet/cheaters/contracts.py
  protostar/starknet/compiler/cairo_compilation.py
  protostar/starknet/compiler/starknet_compilation.py
  protostar/starknet/execution_state.py
  protostar/testing/cairo_cheatcodes/cairo_cheatcode.py
  protostar/testing/cairo_cheatcodes/declare_cairo_cheatcode.py
  protostar/testing/cairo_cheatcodes/deploy_cairo_cheatcode.py
  protostar/testing/cairo_cheatcodes/deploy_contract_cairo_cheatcode.py
  protostar/testing/cairo_cheatcodes/prepare_cairo_cheatcode.py
  protostar/testing/cairo_cheatcodes/roll_cairo_cheatcode.py
  protostar/testing/cairo_cheatcodes/warp_cairo_cheatcode.py
  protostar/testing/cairo_test_runner.py
  protostar/testing/cheatcodes/__init__.py
  protostar/testing/cheatcodes/declare_cheatcode.py
  protostar/testing/cheatcodes/deploy_cheatcode.py
  protostar/testing/cheatcodes/deploy_contract_cheatcode.py
  protostar/testing/cheatcodes/prepare_cheatcode.py
  protostar/testing/environments/cairo_test_cheatcode_factory.py
  protostar/testing/environments/cairo_test_execution_environment.py
  protostar/testing/environments/execution_environment.py
  protostar/testing/environments/fuzz_test_execution_environment.py
  protostar/testing/environments/setup_execution_environment.py
  protostar/testing/environments/test_execution_environment.py
  protostar/testing/starkware/cairo_test_execution_state.py
  protostar/testing/starkware/contract_based_test_execution_state.py
  protostar/testing/starkware/test_execution_state.py
  protostar/testing/test_case_runners/cairo_test_case_runner.py
  protostar/testing/test_case_runners/setup_case_runner.py
  protostar/testing/test_case_runners/test_case_runner_factory.py
  protostar/testing/test_runner.py
  tests/integration/pure_cairo_vm/cheatcodes/contracts/basic_contract.cairo
  tests/integration/pure_cairo_vm/cheatcodes/contracts/basic_with_constructor.cairo
  tests/integration/pure_cairo_vm/cheatcodes/contracts/basic_with_constructor_no_args.cairo
  tests/integration/pure_cairo_vm/cheatcodes/declare/declare_contract_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/declare/declare_contract_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/deploy/deploy_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/deploy/deploy_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/deploy_contract/deploy_contract_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/deploy_contract/deploy_contract_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/prepare/prepare_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/prepare/prepare_contract_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/roll/roll_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/roll/roll_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/warp/warp_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/warp/warp_test.cairo
  tests/integration/pure_cairo_vm/conftest.py
  tests/integration/pure_cairo_vm/test_runner_test/library.cairo
  tests/integration/pure_cairo_vm/test_runner_test/pure_cairo_broken_test.cairo
  tests/integration/pure_cairo_vm/test_runner_test/pure_cairo_test.cairo
  tests/integration/pure_cairo_vm/test_runner_test/test_cairo_vm_runner.py
Labels: size/XXL

#1299 Remove unused gateway facade code
  protostar/starknet_gateway/__init__.py
  protostar/starknet_gateway/account_manager.py
  protostar/starknet_gateway/contract_function_factory.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/starknet_gateway/gateway_response.py
  tests/integration/commands/call_command_test.py
  tests/integration/gateway/gateway_facade_test.py
Labels: size/M

#1304 Argument tokenizer in ProtostarFixture
  tests/integration/_conftest/__init__.py
  tests/integration/_conftest/tokenizer.py
  tests/integration/_conftest/tokenizer_test.py
  tests/integration/protostar_fixture.py
Labels: size/M

#1306 Refine docs — installation.md
  website/docs/tutorials/02-installation.md
Labels: size/S

#1349 New cheatcodes follow up
  protostar/testing/cairo_cheatcodes/cairo_cheatcode.py
  tests/integration/pure_cairo_vm/cheatcodes/deploy/deploy_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/deploy/deploy_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/deploy_contract/deploy_contract_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/deploy_contract/deploy_contract_test.cairo
Labels: size/S

#1311 Refine docs — Dependencies
  website/docs/tutorials/06-dependencies-management.md
Labels: size/M

#1310 Refine docs — Compiling
  website/docs/tutorials/05-compiling.md
Labels: size/S

#1358 Add call cairo cheatcode
  protostar/starknet/cheaters/contracts.py
  protostar/testing/cairo_cheatcodes/call_cairo_cheatcode.py
  protostar/testing/cairo_cheatcodes/prepare_cairo_cheatcode.py
  protostar/testing/environments/cairo_test_cheatcode_factory.py
  tests/integration/pure_cairo_vm/cheatcodes/call/call_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/call/call_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/contracts/basic_contract.cairo
Labels: size/M

#1356 Add invoke cheatcode
  protostar/starknet/cheaters/contracts.py
  protostar/testing/cairo_cheatcodes/invoke_cairo_cheatcode.py
  protostar/testing/environments/cairo_test_cheatcode_factory.py
  tests/integration/pure_cairo_vm/cheatcodes/contracts/proxy_for_basic_contract.cairo
  tests/integration/pure_cairo_vm/cheatcodes/invoke/invoke_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/invoke/invoke_test.cairo
Labels: size/M

#1298 Split `ProtostarFixture` file
  tests/integration/_conftest/__init__.py
  tests/integration/_conftest/gateway_client_tx_interceptor.py
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/_conftest/protostar_fixture_factory.py
  tests/integration/_conftest/spying_gateway_facade_factory.py
  tests/integration/_conftest/transaction_registry.py
  tests/integration/commands/calculate_contract_address_command_test.py
  tests/integration/commands/call_command_test.py
  tests/integration/commands/deploy_account_command_test.py
  tests/integration/commands/invoke_command_test.py
  tests/integration/commands/multicall_command_test.py
  tests/integration/conftest.py
  tests/integration/deploying/declare_command_test.py
  tests/integration/deploying/deploy_command_test.py
  tests/integration/gateway/gateway_facade_test.py
  tests/integration/gateway/multicall_use_case_test.py
  tests/integration/gateway/uint256_as_input_test.py
  tests/integration/pure_cairo_vm/cheatcodes/call/call_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/declare/declare_contract_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/deploy/deploy_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/deploy_contract/deploy_contract_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/invoke/invoke_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/prepare/prepare_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/roll/roll_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/warp/warp_cairo_cheatcode_test.py
  tests/integration/testing_cache/test_cache.py
Labels: size/L

#1307 Refine docs — project initialization
  website/docs/tutorials/03-project-initialization.md
Labels: size/S

#1326 Fixed exit first flag
  protostar/commands/test/testing_live_logger.py
  protostar/testing/__init__.py
  protostar/testing/test_results.py
  protostar/testing/test_shared_tests_state.py
Labels: size/S

#1375 Add proxy test for call cheatcode
  tests/integration/pure_cairo_vm/cheatcodes/call/call_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/call/call_test.cairo
Labels: size/S

#1315 Refactor calculating skipped tests
  protostar/commands/test/messages/testing_summary_message.py
  protostar/commands/test/test_command.py
  protostar/testing/__init__.py
  protostar/testing/test_collector.py
  protostar/testing/testing_summary.py
  tests/integration/conftest.py
Labels: size/M

#1372 Break cyclic imports (`protostar.testing` importing from `protostar.commands`)
  protostar/commands/test/test_command.py
  protostar/commands/test/testing_live_logger.py
  protostar/testing/test_scheduler.py
Labels: size/S

#1371 Fix GLIBC issue
  .github/workflows/assign_issues_to_project.yml
  .github/workflows/assign_pr_author.yml
  .github/workflows/assign_size_label.yml
  .github/workflows/build_binaries.yml
  .github/workflows/build_docs.yml
  .github/workflows/checks.yml
  .github/workflows/deploy_docs.yml
  .github/workflows/test_installation.yml
  .pylintrc
  tests/e2e/test_upgrading.py
Labels: size/S

#1385 Avoid repeating logic in live logger
  protostar/commands/test/testing_live_logger.py
Labels: size/M

#1393 Cairo cheatcode — Prank
  protostar/cairo_testing/cairo_test_cheatcode_factory.py
  protostar/cheatable_starknet/cheatable_cached_state.py
  protostar/cheatable_starknet/cheatable_syscall_handler.py
  protostar/cheatable_starknet/cheatcodes/prank_cairo_cheatcode.py
  protostar/cheatable_starknet/cheaters/contracts.py
  tests/integration/pure_cairo_vm/cheatcodes/prank/prank_cairo_cheatcode_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/prank/prank_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/prank/pranked.cairo
Labels: size/M

#1392 Add `__setup__` for test runner
  protostar/cairo/__init__.py
  protostar/cairo/cairo_function_executor.py
  protostar/cairo/hint_local.py
  protostar/cairo_testing/cairo_execution_environment.py
  protostar/cairo_testing/cairo_injectable_function_runner.py
  protostar/cairo_testing/cairo_setup_execution_environment.py
  protostar/cairo_testing/cairo_test_execution_environment.py
  protostar/cairo_testing/cairo_test_runner.py
  protostar/cairo_testing/cheatcode_factories/__init__.py
  protostar/cairo_testing/cheatcode_factories/cairo_setup_cheatcode_factory.py
  protostar/cairo_testing/cheatcode_factories/cairo_test_cheatcode_factory.py
  protostar/testing/environments/contract_based_test_execution_environment.py
  protostar/testing/environments/execution_environment.py
  protostar/testing/environments/setup_execution_environment.py
  protostar/testing/test_case_runners/standard_test_case_runner.py
  protostar/testing/test_case_runners/test_case_runner.py
  protostar/testing/test_case_runners/test_case_runner_factory.py
  tests/integration/pure_cairo_vm/cheatcodes/call/call_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/declare/declare_contract_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/deploy/deploy_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/deploy_contract/deploy_contract_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/invoke/invoke_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/prepare/prepare_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/roll/roll_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/warp/warp_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/conftest.py
  tests/integration/pure_cairo_vm/contracts/basic_contract.cairo
  tests/integration/pure_cairo_vm/contracts/basic_with_constructor.cairo
  tests/integration/pure_cairo_vm/contracts/basic_with_constructor_no_args.cairo
  tests/integration/pure_cairo_vm/contracts/proxy_for_basic_contract.cairo
  tests/integration/pure_cairo_vm/contracts/roll_warp_tester.cairo
  tests/integration/pure_cairo_vm/test_runner_test/suite_with_setup_and_cheatcodes_test.cairo
  tests/integration/pure_cairo_vm/test_runner_test/suite_with_setup_test.cairo
  tests/integration/pure_cairo_vm/test_runner_test/test_cairo_vm_runner.py
Labels: size/L

#1308 Refine docs — Configuration file
  website/docs/tutorials/04-configuration-file.md
Labels: size/M

#1405 Improve `assert_cairo_test_cases`' feedback
  tests/integration/conftest.py
  tests/integration/conftest_test.py
Labels: size/S

#1406 Setup cases for cairo runner
  protostar/cairo_testing/cairo_test_execution_state.py
  protostar/cairo_testing/cairo_test_runner.py
  protostar/cairo_testing/execution_environments/__init__.py
  protostar/cairo_testing/execution_environments/cairo_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_setup_case_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_setup_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_test_execution_environment.py
  tests/integration/pure_cairo_vm/test_runner_test/suite_with_setup_case_test.cairo
  tests/integration/pure_cairo_vm/test_runner_test/test_cairo_vm_runner.py
Labels: size/M

#1410 Refactor `assert_cairo_test_cases`
  protostar/cairo_testing/cairo_test_execution_state.py
  tests/integration/_conftest/__init__.py
  tests/integration/_conftest/cairo_test_results_assertion.py
  tests/integration/_conftest/cairo_test_results_data.py
  tests/integration/_conftest/cairo_test_results_diff_generator.py
  tests/integration/_conftest/cairo_test_results_diff_generator_test.py
  tests/integration/conftest.py
Labels: size/M

#1411 Fix using contracts in tests with name shortcut
  protostar/compiler/project_compiler.py
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/pure_cairo_vm/cheatcodes/call/call_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/call/call_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/declare/declare_contract_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/declare/declare_contract_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/deploy/deploy_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/deploy_contract/deploy_contract_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/invoke/invoke_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/prank/prank_cairo_cheatcode_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/prank/prank_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/prepare/prepare_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/roll/roll_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/warp/warp_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/conftest.py
  tests/integration/pure_cairo_vm/contracts/pranked.cairo
  tests/integration/pure_cairo_vm/test_runner_test/pure_cairo_test.cairo
  tests/integration/pure_cairo_vm/test_runner_test/test_cairo_vm_runner.py
Labels: size/M

#1416 Move cheatables to cheatables directory
  protostar/cairo_testing/cairo_test_execution_state.py
  protostar/cairo_testing/cheatcode_factories/cairo_setup_cheatcode_factory.py
  protostar/cairo_testing/cheatcode_factories/cairo_test_cheatcode_factory.py
  protostar/cheatable_starknet/cheatables/__init__.py
  protostar/cheatable_starknet/cheatables/cheatable_cached_state.py
  protostar/cheatable_starknet/cheatables/cheatable_entry_point.py
  protostar/cheatable_starknet/cheatables/cheatable_syscall_handler.py
  protostar/cheatable_starknet/cheaters/block_info.py
  protostar/cheatable_starknet/cheaters/contracts.py
Labels: size/S

#1417 Remove dead code (cheaters)
  protostar/cheatable_starknet/cheatables/cheatable_execute_entry_point.py
  protostar/cheatable_starknet/cheatcodes/call_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/invoke_cairo_cheatcode.py
  protostar/cheatable_starknet/cheaters/contracts.py
Labels: size/S

#1364 Add store load cairo cheatcodes
  protostar/cairo_testing/cheatcode_factories/cairo_setup_cheatcode_factory.py
  protostar/cairo_testing/cheatcode_factories/cairo_test_cheatcode_factory.py
  protostar/cheatable_starknet/cheatcodes/load_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/store_cairo_cheatcode.py
  protostar/cheatable_starknet/cheaters/__init__.py
  protostar/cheatable_starknet/cheaters/storage.py
  tests/integration/pure_cairo_vm/cheatcodes/load/load_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/load/load_test.cairo
  tests/integration/pure_cairo_vm/cheatcodes/store/store_cairo_cheatcode_test.py
  tests/integration/pure_cairo_vm/cheatcodes/store/store_test.cairo
  tests/integration/pure_cairo_vm/contracts/block_number_contract.cairo
Labels: size/L

#1400 Protostar-casm
  protostar/cairo/cairo1_test_suite_parser.py
  tests/integration/cairo1/parser_test.py
  tests/integration/cairo1/parser_test/compiled_test_suite.json
Labels: size/M

#1420 Rename cheaters to controllers
  protostar/cairo_testing/cheatcode_factories/cairo_setup_cheatcode_factory.py
  protostar/cairo_testing/cheatcode_factories/cairo_test_cheatcode_factory.py
  protostar/cheatable_starknet/cheatables/cheatable_cached_state.py
  protostar/cheatable_starknet/cheatables/cheatable_execute_entry_point.py
  protostar/cheatable_starknet/cheatcodes/cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/call_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/declare_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/deploy_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/invoke_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/load_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/prank_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/prepare_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/roll_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/store_cairo_cheatcode.py
  protostar/cheatable_starknet/cheatcodes/warp_cairo_cheatcode.py
  protostar/cheatable_starknet/cheaters/__init__.py
  protostar/cheatable_starknet/controllers/__init__.py
  protostar/cheatable_starknet/controllers/block_info.py
  protostar/cheatable_starknet/controllers/contracts.py
  protostar/cheatable_starknet/controllers/storage.py
  protostar/cheatable_starknet/controllers/transaction_revert_exception.py
Labels: size/M

#1427 Rename cheatcodes to hint locals
  protostar/cairo_testing/cairo_cheatcode_factory.py
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cairo_testing/execution_environments/cairo_setup_case_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_setup_execution_environment.py
  protostar/cairo_testing/execution_environments/cairo_test_execution_environment.py
  protostar/cheatable_starknet/callable_hint_locals/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/call_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/callable_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/declare_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/deploy_contract_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/deploy_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/invoke_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/load_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/prank_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/prepare_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/roll_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/store_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/warp_hint_local.py
  protostar/cheatable_starknet/cheatcodes/__init__.py
Labels: size/M
