Repository software-mansion/protostar, pull requests merged in 2023-06, with the labels that each got.

#2026 Create distinctive tags for pre-releases
  .circleci/config.yml
Labels: size/XS

#2027 Hotfix shortstring conversion
  protostar/cairo/short_string.py
Labels: size/XS

#2034 Remove `linked-libraries` mention from docs
  website/docs/cairo-1/07-interacting-with-starknet/09-compiling.md
Labels: size/S

#2037 Version bump
  pyproject.toml
Labels: size/XS

#2036 Printing for test runner
  protostar-rust/Cargo.lock
  protostar-rust/Cargo.toml
  protostar-rust/src/lib.rs
  protostar-rust/src/main.rs
  protostar-rust/src/pretty_printing.rs
  protostar-rust/src/test_stats.rs
Labels: size/M

#2068 Fix paths in rust test runner tests
  protostar-rust/src/lib.rs
  protostar-rust/tests/e2e/running.rs
Labels: size/S

#2070 Check if int is decodable to ascii before doing `short_string_to_str`
  protostar/cairo/short_string.py
  protostar/cairo_testing/cairo_injectable_function_runner.py
  protostar/cheatable_starknet/controllers/io.py
  tests/e2e/cairo1/test_cairo1_testing.py
  tests/e2e/fixtures/cairo1/failing_test.cairo
  tests/integration/cairo1/compiler_bindings/test_print.py
  tests/integration/cairo1/compiler_bindings/test_print/print_test.cairo
  tests/integration/cairo1/misc/test_panic.py
  tests/integration/cairo1/misc/test_panic/panic_test.cairo
Labels: size/M

#2075 Bump devnet to 0.5.3
  poetry.lock
  pyproject.toml
  tests/e2e/test_gateway_commands.py
  tests/integration/cheatcodes/prepare/prepare_test.cairo
  tests/integration/commands/declare_command_test.py
Labels: size/S

#2077 Include corelib in rust runner binary
  protostar-rust/Cargo.lock
  protostar-rust/Cargo.toml
  protostar-rust/src/main.rs
  protostar-rust/tests/e2e/common/runner.rs
  protostar-rust/tests/e2e/running.rs
Labels: size/M

#2061 Add print rust
  protostar-rust/tests/data/print_test/Scarb.toml
  protostar-rust/tests/data/print_test/src/lib.cairo
  protostar-rust/tests/data/print_test/tests/test_print.cairo
  protostar-rust/tests/e2e/running.rs
Labels: size/S

#2086 Add scarb starknet target to template + fix master
  protostar-rust/tests/e2e/running.rs
  templates/cairo1/Scarb.toml
  templates/cairo1_minimal/Scarb.toml
  tests/integration/commands/init_command_test.py
Labels: size/S

#2051 Allow selecting tests by name
  protostar-rust/src/lib.rs
  protostar-rust/src/main.rs
  protostar-rust/tests/data/declare_test/Scarb.toml
  protostar-rust/tests/data/print_test/Scarb.toml
  protostar-rust/tests/data/simple_test/Scarb.toml
  protostar-rust/tests/data/simple_test/tests/test_simple.cairo
  protostar-rust/tests/data/simple_test/tests/without_prefix.cairo
  protostar-rust/tests/e2e/running.rs
Labels: size/L

#2101 Add example project using dispatchers and tests
  protostar-rust/tests/data/dispatchers/Scarb.toml
  protostar-rust/tests/data/dispatchers/src/erc20.cairo
  protostar-rust/tests/data/dispatchers/src/hello_starknet.cairo
  protostar-rust/tests/data/dispatchers/src/lib.cairo
  protostar-rust/tests/data/dispatchers/tests/using_dispatchers.cairo
Labels: size/M

#2106 Add invoke to CLI
  protostar-cli/src/main.rs
  protostar-cli/src/starknet_commands/declare.rs
  protostar-cli/src/starknet_commands/invoke.rs
  protostar-cli/src/starknet_commands/mod.rs
Labels: size/S

#2058 Add MVP for cli
  cast/.cargo/config.toml
  cast/Cargo.lock
  cast/Cargo.toml
  cast/src/lib.rs
  cast/src/main.rs
  cast/src/starknet_commands/call.rs
  cast/src/starknet_commands/declare.rs
  cast/src/starknet_commands/invoke.rs
  cast/src/starknet_commands/mod.rs
Labels: size/XXL

#2122 [CLI] Add deploy command
  cast/Cargo.lock
  cast/Cargo.toml
  cast/src/lib.rs
  cast/src/main.rs
  cast/src/starknet_commands/declare.rs
  cast/src/starknet_commands/deploy.rs
  cast/src/starknet_commands/invoke.rs
  cast/src/starknet_commands/mod.rs
Labels: size/M

#2137 More block-id formats (hex, number)
  cast/src/lib.rs
  cast/src/main.rs
  cast/src/starknet_commands/call.rs
Labels: size/S

#2136 Add max-fee parameter for declare command
  cast/src/main.rs
  cast/src/starknet_commands/declare.rs
Labels: size/S

#2076 Move to starknet.py 0.16.1
  poetry.lock
  protostar.spec
  protostar/cheatable_starknet/callable_hint_locals/assert_expect_call_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/expect_call_hint_local.py
  protostar/cli/signable_command_util.py
  protostar/git/git_helpers.py
  protostar/starknet/data_transformer.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/upgrader/upgrade_manager.py
  pyproject.toml
  tests/_conftest/compiled_account/compiled_account.py
  tests/_conftest/compiled_account/compiler.py
  tests/integration/cheatcodes/send_message_to_l2/address_verification_l1_handler_test.cairo
  tests/integration/cheatcodes/send_message_to_l2/data_transformer_l1_handler_test.cairo
  tests/integration/cheatcodes/send_message_to_l2/send_message_to_l2_test.py
  tests/integration/cheatcodes/send_message_to_l2/simple_l1_handler_test.cairo
  tests/integration/data_transformer/data_transformer_test.py
Labels: size/L

#2140 [CLI] Add setup for tests
  cast/.gitignore
  cast/Cargo.lock
  cast/Cargo.toml
  cast/README.md
  cast/src/lib.rs
  cast/src/main.rs
  cast/tests/data/accounts/accounts.json
  cast/tests/data/accounts/faulty_accounts.json
  cast/tests/data/accounts/invalid_format.json
  cast/tests/data/accounts/user1_representation
  cast/tests/e2e/helpers/devnet.rs
  cast/tests/e2e/helpers/mod.rs
  cast/tests/e2e/helpers/runner.rs
  cast/tests/e2e/main.rs
  cast/tests/utils/prepare_for_tests.sh
Labels: size/L

#2135 Normalize outputs in CLI
  cast/src/lib.rs
  cast/src/main.rs
  cast/src/starknet_commands/call.rs
  cast/src/starknet_commands/declare.rs
  cast/src/starknet_commands/deploy.rs
  cast/src/starknet_commands/invoke.rs
Labels: size/M

#2089 Update 08-scripting.md
  website/docs/cairo-1/07-interacting-with-starknet/08-scripting.md
Labels: size/XS

#2143 Added exit first to the rust runner
  protostar-rust/src/lib.rs
  protostar-rust/src/main.rs
  protostar-rust/src/pretty_printing.rs
  protostar-rust/src/test_stats.rs
  protostar-rust/tests/data/exit_first_test/Scarb.toml
  protostar-rust/tests/data/exit_first_test/src/lib.cairo
  protostar-rust/tests/data/exit_first_test/tests/ext_function_test.cairo
  protostar-rust/tests/data/exit_first_test/tests/test_simple.cairo
  protostar-rust/tests/data/exit_first_test/tests/without_prefix.cairo
  protostar-rust/tests/e2e/running.rs
Labels: size/M

#2123 Add docs for `start_spoof` and `stop_spoof`
  protostar/cheatable_starknet/controllers/transaction_info.py
  website/docs/cairo-1/06-testing/cheatcodes-reference/start_spoof.md
  website/docs/cairo-1/06-testing/cheatcodes-reference/stop_spoof.md
Labels: size/M

#2120 Multiple contracts in package
  protostar-rust/src/cheatcodes_hint_processor.rs
  protostar-rust/src/main.rs
  protostar-rust/tests/data/declare_test/src/contract1.cairo
  protostar-rust/tests/data/declare_test/src/lib.cairo
  protostar-rust/tests/data/declare_test/tests/test_declare.cairo
  protostar-rust/tests/data/multicontract/Scarb.toml
  protostar-rust/tests/data/multicontract/src/contract1.cairo
  protostar-rust/tests/data/multicontract/src/contract2.cairo
  protostar-rust/tests/data/multicontract/src/lib.cairo
  protostar-rust/tests/data/multicontract/tests/ext_function_test.cairo
  protostar-rust/tests/data/multicontract/tests/test_simple.cairo
  protostar-rust/tests/e2e/running.rs
Labels: size/M

#2153 [CLI] `--json` output
  cast/Cargo.lock
  cast/Cargo.toml
  cast/src/lib.rs
  cast/src/main.rs
Labels: size/M

#2155 Pass tilde-expanded accounts file path to commands
  cast/src/main.rs
Labels: size/XS

#2144 Calling and invoking contracts through dispatchers
  protostar-rust/src/cheatcodes_hint_processor.rs
  protostar-rust/src/lib.rs
  protostar-rust/tests/data/dispatchers/Scarb.toml
  protostar-rust/tests/data/dispatchers/src/erc20.cairo
  protostar-rust/tests/data/dispatchers/src/hello_starknet.cairo
  protostar-rust/tests/data/dispatchers/tests/using_dispatchers.cairo
  protostar-rust/tests/e2e/running.rs
Labels: size/XL
