Repository software-mansion/protostar, pull requests merged in 2023-04, with the labels that each got.

#1700 Avoid boilerplate in declare cairo1 tests
  tests/integration/cairo1_hint_locals/declare/declare_test.cairo
Labels: size/S

#1710 Add a test for `deploy_contract`
  tests/integration/cairo1_compiler_bindings/library_functions_test.py
  tests/integration/cairo1_compiler_bindings/library_functions_test/deploy_contract_test.cairo
Labels: size/S

#1702 Prepare hint local
  protostar/cheatable_starknet/callable_hint_locals/deploy_contract_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/prepare_hint_local.py
  protostar/cheatable_starknet/controllers/contracts.py
  tests/integration/cairo1_hint_locals/prepare/data/minimal_no_args.cairo
  tests/integration/cairo1_hint_locals/prepare/data/minimal_with_args.cairo
  tests/integration/cairo1_hint_locals/prepare/prepare_test.cairo
  tests/integration/cairo1_hint_locals/prepare/test_prepare.py
Labels: size/M

#1637 Move hooks setup to corresponding HintLocal constructors
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cheatable_starknet/callable_hint_locals/expect_call_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/expect_events_hint_local.py
  protostar/cheatable_starknet/controllers/expect_call_controller.py
  protostar/cheatable_starknet/controllers/expect_events_controller.py
Labels: size/S

#1703 Replace all StarkNet occurrences with Starknet
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  protostar/cli/common_arguments.py
  protostar/cli/network_command_util.py
  protostar/cli/network_command_util_test.py
  protostar/commands/call/call_command.py
  protostar/commands/declare_command.py
  protostar/commands/invoke/invoke_command.py
  protostar/starknet/pass_managers.py
  protostar/starknet_gateway/network_config.py
  protostar/testing/examples/basic_with_constructor.cairo
  protostar/testing/test_environment_exceptions.py
  pyproject.toml
  tests/_conftest/compiled_account/account_contract_with_validate_deploy.cairo
  tests/e2e/fixtures/basic.cairo
  tests/e2e/fixtures/formatted.cairo
  tests/e2e/fixtures/proxy_contract.cairo
  tests/e2e/fixtures/unformatted.cairo
  tests/integration/cheatcodes/declare/proxy_contract.cairo
  tests/integration/cheatcodes/deploy_contract/basic_with_constructor.cairo
  tests/integration/cheatcodes/deploy_contract/basic_with_constructor_no_args.cairo
  tests/integration/cheatcodes/deploy_contract/proxy_contract.cairo
  tests/integration/cheatcodes/send_message_to_l2/simple_l1_handler_test.cairo
  website/docs/cli-reference.md
  website/docs/tutorials/01-introduction.md
  website/docs/tutorials/05-compiling.md
  website/docs/tutorials/07-testing/02-cheatcodes/expect-events.md
  website/docs/tutorials/07-testing/02-cheatcodes/send-message-to-l2.md
  website/docs/tutorials/07-testing/04-e2e.md
  website/docs/tutorials/07-testing/README.md
  website/docs/tutorials/09-interacting-with-starknet/03-declare.md
  website/docs/tutorials/09-interacting-with-starknet/05-deploy-account.md
  website/docs/tutorials/09-interacting-with-starknet/README.md
  website/docs/tutorials/09-interacting-with-starknet/_category_.yaml
  website/docusaurus.config.js
  website/src/pages/index.tsx
  website/static/manifest.json
Labels: size/M

#1690 Document declare cheatcode in cairo1
  website/docs/tutorials/08-cairo-1-support/03-cheatcodes/README.md
  website/docs/tutorials/08-cairo-1-support/03-cheatcodes/declare-cairo0.md
  website/docs/tutorials/08-cairo-1-support/03-cheatcodes/declare.md
Labels: size/S

#1678 Adapt CLI to Starknet 0.11.0
  poetry.lock
  protostar/cairo_testing/cairo1_test_runner.py
  protostar/cheatable_starknet/callable_hint_locals/declare_hint_local.py
  protostar/commands/__init__.py
  protostar/commands/cairo1_commands/__init__.py
  protostar/commands/cairo1_commands/declare_cairo1_command.py
  protostar/commands/declare/__init__.py
  protostar/commands/declare/declare_command.py
  protostar/commands/declare/declare_messages.py
  protostar/compiler/project_compiler.py
  protostar/composition_root.py
  protostar/starknet_gateway/gateway_facade.py
  protostar/testing/test_runner.py
  tests/e2e/test_gateway_commands.py
  tests/e2e/test_gateway_commands/balance.cairo
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/_conftest/protostar_fixture_factory.py
  tests/integration/commands/declare_command_test.py
  tests/integration/commands/declare_command_test/balance.cairo
  tests/integration/commands/deploy_command_test.py
  website/docs/cli-reference.md
Labels: size/XL

#1752 Test `deploy_contract_cairo0`
  protostar/cairo_testing/cairo_hint_local_factory.py
  protostar/cheatable_starknet/callable_hint_locals/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/deploy_contract_hint_local.py
  tests/integration/cairo1_hint_locals/deploy_contract_cairo0/data/cairo0.cairo
  tests/integration/cairo1_hint_locals/deploy_contract_cairo0/data/cairo0_w_ctor.cairo
  tests/integration/cairo1_hint_locals/deploy_contract_cairo0/data/cairo0_w_ctor_error.cairo
  tests/integration/cairo1_hint_locals/deploy_contract_cairo0/deploy_contract_cairo0_test.cairo
  tests/integration/cairo1_hint_locals/deploy_contract_cairo0/test_deploy_contract_cairo0.py
Labels: size/M

#1766 Update declare and declare-cairo0 docs
  website/docs/tutorials/08-cairo-1-support/03-cheatcodes/declare-cairo0.md
  website/docs/tutorials/08-cairo-1-support/03-cheatcodes/declare.md
Labels: size/XS

#1773 Add call Cairo 1 docs
  website/docs/tutorials/08-cairo-1-support/03-cheatcodes/call.md
Labels: size/S

#1769 Added invoke docs
  website/docs/tutorials/08-cairo-1-support/03-cheatcodes/call.md
  website/docs/tutorials/08-cairo-1-support/03-cheatcodes/invoke.md
Labels: size/S

#1736 Add test which imports from a contract
  tests/integration/cairo1_compiler_bindings/data/external_contract/cairo_project.toml
  tests/integration/cairo1_compiler_bindings/data/external_contract/contract.cairo
  tests/integration/cairo1_compiler_bindings/data/external_contract/lib.cairo
  tests/integration/cairo1_compiler_bindings/tests_collector_and_compiler_test.py
  tests/integration/cairo1_compiler_bindings/tests_collector_and_compiler_test/test_with_contract_deps.cairo
Labels: size/S

#1775 Release fixes
  binary_entrypoint.py
  protostar/commands/cairo1_commands/test_cairo1_command.py
  protostar/commands/test/test_command.py
  templates/cairo1/src/main.cairo
Labels: size/S

#1776 e2e tests for invalid contracts
  tests/e2e/cairo1/test_cairo1_building.py
Labels: size/S

#1777 Use `deploy_contract` in call tests
  tests/integration/cairo1_hint_locals/call/call_test.cairo
Labels: size/S

#1722 Produce both sierra and casm outputs when build-cairo1
  protostar/commands/cairo1_commands/build_cairo1_command.py
  tests/e2e/cairo1/test_cairo1_building.py
  tests/e2e/cairo_0_1_mixed/test_cairo_0_1_mixed_building.py
Labels: size/S

#1798 Fix declaring two contracts next to each other
  protostar/cheatable_starknet/controllers/contracts.py
  tests/integration/cairo1_hint_locals/declare/data/simple/cairo_project.toml
  tests/integration/cairo1_hint_locals/declare/data/simple/lib.cairo
  tests/integration/cairo1_hint_locals/declare/declare_test.cairo
  tests/integration/cairo1_hint_locals/declare/test_declare.py
Labels: size/S

#1790 Plugged in `available_gas`
  protostar/cairo_testing/cairo1_test_collector.py
  protostar/testing/test_collector.py
Labels: size/S

#1813 Fix misleading cairo1 docs
  website/docs/tutorials/08-cairo-1-support/03-testing.md
Labels: size/S

#1822 Remove cairo1 flag from test command
  protostar/commands/cairo1_commands/test_cairo1_command.py
  protostar/commands/test/test_command.py
  pyproject.toml
  tests/integration/_conftest/protostar_fixture.py
  tests/integration/_conftest/protostar_fixture_factory.py
  tests/integration/cairo1_hint_locals/call/test_call.py
  tests/integration/cairo1_hint_locals/declare/test_declare.py
  tests/integration/cairo1_hint_locals/deploy/test_deploy.py
  tests/integration/cairo1_hint_locals/deploy_contract/test_deploy_contract.py
  tests/integration/cairo1_hint_locals/deploy_contract_cairo0/test_deploy_contract_cairo0.py
  tests/integration/cairo1_hint_locals/invoke/test_invoke.py
  tests/integration/cairo1_hint_locals/prepare/test_prepare.py
  tests/integration/pure_cairo_vm/cairo1_integration/cairo1_runner_test.py
  tests/integration/pure_cairo_vm/cheatcodes/declare_cairo0_cheatcode_test.py
Labels: size/M

#1791 Added `available_gas` docs
  website/docs/tutorials/08-cairo-1-support/05-gas.md
Labels: size/S

#1786 Improve new template scarb compatibility
  protostar/commands/init/project_creator/new_project_creator.py
  templates/cairo1/hello_starknet/cairo_project.toml
  templates/cairo1/hello_starknet/src/business_logic.cairo
  templates/cairo1/hello_starknet/src/business_logic/utils.cairo
  templates/cairo1/hello_starknet/src/contracts.cairo
  templates/cairo1/hello_starknet/src/contracts/hello_starknet.cairo
  templates/cairo1/hello_starknet/src/lib.cairo
  templates/cairo1/protostar.toml
  templates/cairo1/src/cairo_project.toml
  templates/cairo1/tests/test_utils.cairo
  tests/integration/commands/init_command_test/project_name/hello_starknet/cairo_project.toml
  tests/integration/commands/init_command_test/project_name/hello_starknet/src/business_logic.cairo
  tests/integration/commands/init_command_test/project_name/hello_starknet/src/business_logic/utils.cairo
  tests/integration/commands/init_command_test/project_name/hello_starknet/src/contracts.cairo
  tests/integration/commands/init_command_test/project_name/hello_starknet/src/contracts/hello_starknet.cairo
  tests/integration/commands/init_command_test/project_name/hello_starknet/src/lib.cairo
  tests/integration/commands/init_command_test/project_name/protostar.toml
  tests/integration/commands/init_command_test/project_name/src/cairo_project.toml
  tests/integration/commands/init_command_test/project_name/tests/test_utils.cairo
Labels: size/S

#1787 Add tests to cairo1 project creation logic
  protostar/commands/init/project_creator/new_project_creator.py
  tests/e2e/cairo1/test_cairo1_init.py
Labels: size/S

#1828 Removed not relevant todos
  protostar/cairo/cairo_compiler.py
  protostar/cairo_testing/cairo1_test_runner.py
  protostar/cairo_testing/execution_environments/cairo_test_execution_environment.py
  protostar/cheatable_starknet/controllers/contracts.py
  protostar/commands/init/project_creator/_project_creator.py
  protostar/profiler/contract_profiler.py
  protostar/profiler/transaction_profiler.py
  protostar/self/protostar_directory.py
  protostar/starknet/cheatable_execute_entry_point.py
  protostar/starknet/cheatable_syscall_handler.py
  protostar/starknet/cheatcode.py
  protostar/starknet/starknet_compiler.py
  protostar/starknet_gateway/account_tx_version_detector.py
  protostar/testing/environments/contract_based_test_execution_environment.py
  tests/e2e/conftest.py
  tests/e2e/test_gateway_commands.py
  tests/integration/cairo1_compiler_bindings/tests_collector_and_compiler_test.py
  tests/integration/commands/declare_command_test.py
Labels: size/S

#1833 Rename TestCaseWithOffset
  protostar/cairo_testing/cairo1_test_runner.py
  protostar/testing/test_case_runners/cairo1_test_case_runner.py
  protostar/testing/test_suite.py
Labels: size/S

#1641 Fetch linked-libraries from Scarb metadata
  .github/workflows/checks.yml
  protostar/cheatable_starknet/callable_hint_locals/declare_hint_local.py
  protostar/cli/common_arguments.py
  protostar/commands/cairo1_commands/build_cairo1_command.py
  protostar/commands/cairo1_commands/fetch_from_scarb.py
  protostar/commands/cairo1_commands/test_cairo1_command.py
  tests/e2e/cairo1/test_building_contracts_scarb.py
  tests/e2e/cairo1/test_cairo1_building.py
  tests/e2e/cairo1/test_cairo1_testing.py
  tests/e2e/cairo1/test_testing_scarb.py
  tests/e2e/fixtures/cairo1_project/protostar.toml
  tests/e2e/fixtures/scarb_integration/libraries/Scarb.toml
  tests/e2e/fixtures/scarb_integration/libraries/cairo_project.toml
  tests/e2e/fixtures/scarb_integration/libraries/libraries/external_lib_bar/Scarb.toml
  tests/e2e/fixtures/scarb_integration/libraries/libraries/external_lib_bar/cairo_project.toml
  tests/e2e/fixtures/scarb_integration/libraries/libraries/external_lib_bar/src/bar.cairo
  tests/e2e/fixtures/scarb_integration/libraries/libraries/external_lib_bar/src/lib.cairo
  tests/e2e/fixtures/scarb_integration/libraries/libraries/external_lib_foo/Scarb.toml
  tests/e2e/fixtures/scarb_integration/libraries/libraries/external_lib_foo/cairo_project.toml
  tests/e2e/fixtures/scarb_integration/libraries/libraries/external_lib_foo/src/foo.cairo
  tests/e2e/fixtures/scarb_integration/libraries/libraries/external_lib_foo/src/lib.cairo
  tests/e2e/fixtures/scarb_integration/libraries/protostar.toml
  tests/e2e/fixtures/scarb_integration/libraries/src/contract.cairo
  tests/e2e/fixtures/scarb_integration/libraries/src/lib.cairo
  tests/e2e/fixtures/scarb_integration/libraries/tests/test_contract.cairo
  tests/e2e/fixtures/scarb_integration/libraries/tests/test_pure_cairo.cairo
  tests/e2e/fixtures/scarb_integration/modules/Scarb.toml
  tests/e2e/fixtures/scarb_integration/modules/cairo_project.toml
  tests/e2e/fixtures/scarb_integration/modules/protostar.toml
  tests/e2e/fixtures/scarb_integration/modules/src/contract.cairo
  tests/e2e/fixtures/scarb_integration/modules/src/internal_mod_bar.cairo
  tests/e2e/fixtures/scarb_integration/modules/src/internal_mod_bar/bar.cairo
  tests/e2e/fixtures/scarb_integration/modules/src/internal_mod_foo.cairo
  tests/e2e/fixtures/scarb_integration/modules/src/internal_mod_foo/foo.cairo
  tests/e2e/fixtures/scarb_integration/modules/src/lib.cairo
  tests/e2e/fixtures/scarb_integration/modules/tests/test_contract.cairo
  tests/e2e/fixtures/scarb_integration/modules/tests/test_pure_cairo.cairo
  tests/e2e/fixtures/scarb_integration/multiple_contracts/Scarb.toml
  tests/e2e/fixtures/scarb_integration/multiple_contracts/bar_contract/Scarb.toml
  tests/e2e/fixtures/scarb_integration/multiple_contracts/bar_contract/cairo_project.toml
  tests/e2e/fixtures/scarb_integration/multiple_contracts/bar_contract/src/bar.cairo
  tests/e2e/fixtures/scarb_integration/multiple_contracts/bar_contract/src/lib.cairo
  tests/e2e/fixtures/scarb_integration/multiple_contracts/cairo_project.toml
  tests/e2e/fixtures/scarb_integration/multiple_contracts/foo_contract/Scarb.toml
  tests/e2e/fixtures/scarb_integration/multiple_contracts/foo_contract/cairo_project.toml
  tests/e2e/fixtures/scarb_integration/multiple_contracts/foo_contract/src/foo.cairo
  tests/e2e/fixtures/scarb_integration/multiple_contracts/foo_contract/src/lib.cairo
  tests/e2e/fixtures/scarb_integration/multiple_contracts/protostar.toml
  tests/e2e/fixtures/scarb_integration/multiple_contracts/src/lib.cairo
  tests/e2e/fixtures/scarb_integration/multiple_contracts/tests/test_bar.cairo
  tests/e2e/fixtures/scarb_integration/multiple_contracts/tests/test_foo.cairo
  tests/e2e/fixtures/scarb_integration/online_dependencies/Scarb.toml
  tests/e2e/fixtures/scarb_integration/online_dependencies/cairo_project.toml
  tests/e2e/fixtures/scarb_integration/online_dependencies/protostar.toml
  tests/e2e/fixtures/scarb_integration/online_dependencies/src/contract.cairo
  tests/e2e/fixtures/scarb_integration/online_dependencies/src/lib.cairo
  tests/e2e/fixtures/scarb_integration/online_dependencies/tests/test_contract.cairo
  tests/e2e/fixtures/scarb_integration/online_dependencies/tests/test_pure_cairo.cairo
  website/docs/cli-reference.md
Labels: size/L

#1785 Extend docs about project initialization
  website/docs/tutorials/08-cairo-1-support/01-requirements.md
  website/docs/tutorials/08-cairo-1-support/01-understanding-cairo-packages.md
  website/docs/tutorials/08-cairo-1-support/02-project-initialization.md
  website/docs/tutorials/08-cairo-1-support/03-protostar-toml.md
  website/docs/tutorials/08-cairo-1-support/04-testing.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/README.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/call.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/declare-cairo0.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/declare.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/deploy.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/invoke.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/prepare.md
  website/docs/tutorials/08-cairo-1-support/06-interacting-with-starknet/README.md
  website/docs/tutorials/08-cairo-1-support/06-interacting-with-starknet/declare.md
Labels: size/L

#1839 Create pull_request_template.md
  .github/pull_request_template.md
Labels: size/XS

#1711 Protostar Shell MVP design document
  design_docs/shell.md
Labels: size/M

#1811 Add cairo1 prank cheatcode documentation
  website/docs/tutorials/08-cairo-1-support/03-cheatcodes/start_prank.md
  website/docs/tutorials/08-cairo-1-support/03-cheatcodes/stop_prank.md
Labels: size/S

#1842 added compiler version info to `--version`
  protostar.spec
  protostar/protostar_cli.py
  protostar/self/protostar_directory.py
  tests/e2e/test_misc_commands.py
  website/docs/cli-reference.md
  website/docs/tutorials/05-compiling.md
Labels: size/S

#1840 Added `deploy_contract` docs
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/deploy_contract.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/deploy_contract_cairo0.md
Labels: size/S

#1643 Add build-cairo1 docs
  website/docs/tutorials/08-cairo-1-support/06-compiling.md
Labels: size/S

#1810 Add cairo1 prank cheatcode
  protostar/cheatable_starknet/callable_hint_locals/__init__.py
  protostar/cheatable_starknet/callable_hint_locals/start_prank_hint_local.py
  protostar/cheatable_starknet/callable_hint_locals/stop_prank_hint_local.py
  protostar/cheatable_starknet/controllers/contracts.py
  tests/integration/cairo1/hint_locals/prank/data/pranked/cairo_project.toml
  tests/integration/cairo1/hint_locals/prank/data/pranked/lib.cairo
  tests/integration/cairo1/hint_locals/prank/data/with_constructor/cairo_project.toml
  tests/integration/cairo1/hint_locals/prank/data/with_constructor/lib.cairo
  tests/integration/cairo1/hint_locals/prank/prank_test.cairo
  tests/integration/cairo1/hint_locals/prank/test_prank.py
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/start_prank.md
  website/docs/tutorials/08-cairo-1-support/05-cheatcodes/stop_prank.md
Labels: size/M

#1821 Prepare extensive tests
  tests/integration/cairo1/hint_locals/prepare/data/cairo0.cairo
  tests/integration/cairo1/hint_locals/prepare/data/cairo0_w_ctor.cairo
  tests/integration/cairo1/hint_locals/prepare/data/cairo0_w_ctor_no_args.cairo
  tests/integration/cairo1/hint_locals/prepare/prepare_test.cairo
  tests/integration/cairo1/hint_locals/prepare/test_prepare.py
Labels: size/M
